In [1]:
#Data Cleaning
import pandas as pd
import openpyxl
print(openpyxl.__version__)

3.1.5

In [2]:
df = pd.read_excel(r"C:\Users\ASUS\Desktop\DataPy\cleandata.xlsx") 
df

,EmployeeID,Name,Age,Department,Salary,JoinDate,City,Email
0,101,Alice,25.0,HR,45000.0,2023-01-15,Kathmandu,alice@example.com
1,102,Bob,NaN,IT,55000.0,2022-05-10,Pokhara,bob@example.com
2,103,Charlie,29.0,Finance,60000.0,2021-03-12,NaN,charlie@example.com
3,104,Dana,35.0,IT,NaN,2020-11-01,Lalitpur,dana@example
4,104,Dana,35.0,IT,NaN,2020-11-01,Lalitpur,dana@example
5,105,NaN,42.0,HR,52000.0,2019-07-20,Bhaktapur,eva@example.com
6,106,Frank,-5.0,Sales,48000.0,2024-02-30,Biratnagar,frank@example.com
7,107,Grace,31.0,Marketing,70000.0,2022-08-18,Kathmandu,grace@example.com
8,108,Henry,28.0,IT,58000.0,2023-04-05,Pokhara,henry@example.com
9,109,Ivy,27.0,Finance,61000.0,2023-06-25,Kathmandu,ivy@example.com

In [3]:
df.drop_duplicates()   #remove duplicates

,EmployeeID,Name,Age,Department,Salary,JoinDate,City,Email
0,101,Alice,25.0,HR,45000.0,2023-01-15,Kathmandu,alice@example.com
1,102,Bob,NaN,IT,55000.0,2022-05-10,Pokhara,bob@example.com
2,103,Charlie,29.0,Finance,60000.0,2021-03-12,NaN,charlie@example.com
3,104,Dana,35.0,IT,NaN,2020-11-01,Lalitpur,dana@example
5,105,NaN,42.0,HR,52000.0,2019-07-20,Bhaktapur,eva@example.com
6,106,Frank,-5.0,Sales,48000.0,2024-02-30,Biratnagar,frank@example.com
7,107,Grace,31.0,Marketing,70000.0,2022-08-18,Kathmandu,grace@example.com
8,108,Henry,28.0,IT,58000.0,2023-04-05,Pokhara,henry@example.com
9,109,Ivy,27.0,Finance,61000.0,2023-06-25,Kathmandu,ivy@example.com

In [4]:
df = df.drop_duplicates() 
df

,EmployeeID,Name,Age,Department,Salary,JoinDate,City,Email
0,101,Alice,25.0,HR,45000.0,2023-01-15,Kathmandu,alice@example.com
1,102,Bob,NaN,IT,55000.0,2022-05-10,Pokhara,bob@example.com
2,103,Charlie,29.0,Finance,60000.0,2021-03-12,NaN,charlie@example.com
3,104,Dana,35.0,IT,NaN,2020-11-01,Lalitpur,dana@example
5,105,NaN,42.0,HR,52000.0,2019-07-20,Bhaktapur,eva@example.com
6,106,Frank,-5.0,Sales,48000.0,2024-02-30,Biratnagar,frank@example.com
7,107,Grace,31.0,Marketing,70000.0,2022-08-18,Kathmandu,grace@example.com
8,108,Henry,28.0,IT,58000.0,2023-04-05,Pokhara,henry@example.com
9,109,Ivy,27.0,Finance,61000.0,2023-06-25,Kathmandu,ivy@example.com

In [7]:
#df.drop(columns = 'Age') # drop that column

df['Name'].str.strip()

0      Alice
1        Bob
2    Charlie
3       Dana
5        NaN
6      Frank
7      Grace
8      Henry
9        Ivy
Name: Name, dtype: object

In [8]:
#clean phone number
#df['phone_number'].str.replace('^a-zA-Z0-9', '')

#remove NAN
df

AttributeError: Can only use .str accessor with string values!