In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("sales_cohort_data.csv")

In [4]:
df

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount
0,ORD_10000,CUST_131,2024-01-01,West,Technology,SMB,594.27,NaN
1,ORD_10001,CUST_111,2024-01-02,East,Furniture,Consumer,234.70,0.00
2,ORD_10002,CUST_117,2024-01-03,East,Technology,SMB,847.50,0.00
3,ORD_10003,CUST_106,2024-01-04,East,Furniture,SMB,560.86,0.15
4,ORD_10004,CUST_123,2024-01-05,West,Furniture,SMB,369.73,0.05
...,...,...,...,...,...,...,...,...
195,ORD_10195,CUST_129,2024-07-14,South,Technology,SMB,479.84,0.10
196,ORD_10196,CUST_106,2024-07-15,South,Furniture,SMB,217.12,0.10
197,ORD_10197,CUST_128,2024-07-16,South,Furniture,SMB,268.44,0.15
198,ORD_10198,CUST_142,2024-07-17,South,Furniture,SMB,502.80,0.10
199,ORD_10199,CUST_122,2024-07-18,East,Furniture,SMB,163.72,0.00

In [4]:
df.head(6)

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount
0,ORD_10000,CUST_131,2024-01-01,West,Technology,SMB,594.27,NaN
1,ORD_10001,CUST_111,2024-01-02,East,Furniture,Consumer,234.70,0.00
2,ORD_10002,CUST_117,2024-01-03,East,Technology,SMB,847.50,0.00
3,ORD_10003,CUST_106,2024-01-04,East,Furniture,SMB,560.86,0.15
4,ORD_10004,CUST_123,2024-01-05,West,Furniture,SMB,369.73,0.05
5,ORD_10005,CUST_111,2024-01-06,South,Office Supplies,Consumer,20.79,NaN

In [5]:
df.tail(6)

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount
194,ORD_10194,CUST_115,2024-07-13,West,Office Supplies,SMB,128.44,0.05
195,ORD_10195,CUST_129,2024-07-14,South,Technology,SMB,479.84,0.10
196,ORD_10196,CUST_106,2024-07-15,South,Furniture,SMB,217.12,0.10
197,ORD_10197,CUST_128,2024-07-16,South,Furniture,SMB,268.44,0.15
198,ORD_10198,CUST_142,2024-07-17,South,Furniture,SMB,502.80,0.10
199,ORD_10199,CUST_122,2024-07-18,East,Furniture,SMB,163.72,0.00

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          200 non-null    str
 1   customer_id       200 non-null    str
 2   order_date        200 non-null    str
 3   region            200 non-null    str
 4   category          200 non-null    str
 5   customer_segment  200 non-null    str
 6   sales_amount      200 non-null    float64
 7   discount          183 non-null    float64
dtypes: float64(2), str(6)
memory usage: 12.6 KB

In [7]:
df.describe()

       sales_amount    discount
count    200.000000  183.000000
mean     399.738950    0.056557
std      300.340069    0.062552
min       10.580000    0.000000
25%      144.337500    0.000000
50%      341.795000    0.050000
75%      537.065000    0.100000
max     1189.680000    0.200000

In [9]:
df.isnull().sum()

order_id             0
customer_id          0
order_date           0
region               0
category             0
customer_segment     0
sales_amount         0
discount            17
dtype: int64

In [11]:
df.shape

(200, 8)

In [13]:
df["order_date"] = pd.to_datetime(df["order_date"])

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          200 non-null    str
 1   customer_id       200 non-null    str
 2   order_date        200 non-null    datetime64[us]
 3   region            200 non-null    str
 4   category          200 non-null    str
 5   customer_segment  200 non-null    str
 6   sales_amount      200 non-null    float64
 7   discount          183 non-null    float64
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 12.6 KB

# Group By

In [5]:
region_sales = df.groupby("region") ["sales_amount"].mean()   #single column grouping
print(region_sales)

region
East     413.868837
North    387.849592
South    375.271639
West     430.962340
Name: sales_amount, dtype: float64

In [6]:
cat_region = df.groupby(["category","region"]) ["sales_amount"].sum()  # multi column grouping ("Hierarchical Index) 
print(cat_region)

category         region
Furniture        East       6709.96
                 North      5982.39
                 South     10013.60
                 West       5194.94
Office Supplies  East        658.87
                 North      1043.10
                 South      1221.28
                 West       1211.94
Technology       East      10427.53
                 North     11979.14
                 South     11656.69
                 West      13848.35
Name: sales_amount, dtype: float64

In [18]:
pivoted_view = cat_region.unstack(level="region")  #Unstacking into tabular format
print(pivoted_view)

region               East     North     South      West
category
Furniture         6709.96   5982.39  10013.60   5194.94
Office Supplies    658.87   1043.10   1221.28   1211.94
Technology       10427.53  11979.14  11656.69  13848.35

# Transform

In [8]:
df["cat_avg_sales"] = df.groupby("category")["sales_amount"].transform("mean")
print(df["cat_avg_sales"])

0      656.324795
1      357.703718
2      656.324795
3      357.703718
4      357.703718
          ...
195    656.324795
196    357.703718
197    357.703718
198    357.703718
199    357.703718
Name: cat_avg_sales, Length: 200, dtype: float64

In [13]:
df

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount,cat_avg_sales,region_avg,dev_from_avg
0,ORD_10000,CUST_131,2024-01-01,West,Technology,SMB,594.27,0.05,656.324795,430.962340,163.307660
1,ORD_10001,CUST_111,2024-01-02,East,Furniture,Consumer,234.70,0.00,357.703718,413.868837,-179.168837
2,ORD_10002,CUST_117,2024-01-03,East,Technology,SMB,847.50,0.00,656.324795,413.868837,433.631163
3,ORD_10003,CUST_106,2024-01-04,East,Furniture,SMB,560.86,0.15,357.703718,413.868837,146.991163
4,ORD_10004,CUST_123,2024-01-05,West,Furniture,SMB,369.73,0.05,357.703718,430.962340,-61.232340
...,...,...,...,...,...,...,...,...,...,...,...
195,ORD_10195,CUST_129,2024-07-14,South,Technology,SMB,479.84,0.10,656.324795,375.271639,104.568361
196,ORD_10196,CUST_106,2024-07-15,South,Furniture,SMB,217.12,0.10,357.703718,375.271639,-158.151639
197,ORD_10197,CUST_128,2024-07-16,South,Furniture,SMB,268.44,0.15,357.703718,375.271639,-106.831639
198,ORD_10198,CUST_142,2024-07-17,South,Furniture,SMB,502.80,0.10,357.703718,375.271639,127.528361
199,ORD_10199,CUST_122,2024-07-18,East,Furniture,SMB,163.72,0.00,357.703718,413.868837,-250.148837

In [9]:
df["region_avg"] = df.groupby("region") ["sales_amount"].transform("mean")
print(df["region_avg"])

0      430.962340
1      413.868837
2      413.868837
3      413.868837
4      430.962340
          ...
195    375.271639
196    375.271639
197    375.271639
198    375.271639
199    413.868837
Name: region_avg, Length: 200, dtype: float64

In [10]:
df["dev_from_avg"] = df["sales_amount"] - df["region_avg"]
print(df["dev_from_avg"] )

0      163.307660
1     -179.168837
2      433.631163
3      146.991163
4      -61.232340
          ...
195    104.568361
196   -158.151639
197   -106.831639
198    127.528361
199   -250.148837
Name: dev_from_avg, Length: 200, dtype: float64

In [12]:
df

,order_id,customer_id,order_date,region,category,customer_segment,sales_amount,discount,cat_avg_sales,region_avg,dev_from_avg
0,ORD_10000,CUST_131,2024-01-01,West,Technology,SMB,594.27,0.05,656.324795,430.962340,163.307660
1,ORD_10001,CUST_111,2024-01-02,East,Furniture,Consumer,234.70,0.00,357.703718,413.868837,-179.168837
2,ORD_10002,CUST_117,2024-01-03,East,Technology,SMB,847.50,0.00,656.324795,413.868837,433.631163
3,ORD_10003,CUST_106,2024-01-04,East,Furniture,SMB,560.86,0.15,357.703718,413.868837,146.991163
4,ORD_10004,CUST_123,2024-01-05,West,Furniture,SMB,369.73,0.05,357.703718,430.962340,-61.232340
...,...,...,...,...,...,...,...,...,...,...,...
195,ORD_10195,CUST_129,2024-07-14,South,Technology,SMB,479.84,0.10,656.324795,375.271639,104.568361
196,ORD_10196,CUST_106,2024-07-15,South,Furniture,SMB,217.12,0.10,357.703718,375.271639,-158.151639
197,ORD_10197,CUST_128,2024-07-16,South,Furniture,SMB,268.44,0.15,357.703718,375.271639,-106.831639
198,ORD_10198,CUST_142,2024-07-17,South,Furniture,SMB,502.80,0.10,357.703718,375.271639,127.528361
199,ORD_10199,CUST_122,2024-07-18,East,Furniture,SMB,163.72,0.00,357.703718,413.868837,-250.148837

In [11]:
df["discount"] = df["discount"].fillna(df.groupby("customer_segment") ["discount"].transform("median"))
print(df["discount"])

0      0.05
1      0.00
2      0.00
3      0.15
4      0.05
       ...
195    0.10
196    0.10
197    0.15
198    0.10
199    0.00
Name: discount, Length: 200, dtype: float64

In [15]:
low_amount = df[df["dev_from_avg"] < 0]
print(low_amount)

      order_id customer_id  order_date region         category  \
1    ORD_10001    CUST_111  2024-01-02   East        Furniture
4    ORD_10004    CUST_123  2024-01-05   West        Furniture
5    ORD_10005    CUST_111  2024-01-06  South  Office Supplies
9    ORD_10009    CUST_140  2024-01-10  South       Technology
12   ORD_10012    CUST_128  2024-01-13   East  Office Supplies
..         ...         ...         ...    ...              ...
193  ORD_10193    CUST_124  2024-07-12   East        Furniture
194  ORD_10194    CUST_115  2024-07-13   West  Office Supplies
196  ORD_10196    CUST_106  2024-07-15  South        Furniture
197  ORD_10197    CUST_128  2024-07-16  South        Furniture
199  ORD_10199    CUST_122  2024-07-18   East        Furniture

    customer_segment  sales_amount  discount  cat_avg_sales  region_avg  \
1           Consumer        234.70      0.00     357.703718  413.868837
4                SMB        369.73      0.05     357.703718  430.962340
5           Consumer         20.79      0.05      84.391633  375.271639
9           Consumer        337.48      0.05     656.324795  375.271639
12               SMB         10.58      0.05      84.391633  413.868837
..               ...           ...       ...            ...         ...
193         Consumer        155.69      0.05     357.703718  413.868837
194              SMB        128.44      0.05      84.391633  430.962340
196              SMB        217.12      0.10     357.703718  375.271639
197              SMB        268.44      0.15     357.703718  375.271639
199              SMB        163.72      0.00     357.703718  413.868837

     dev_from_avg
1     -179.168837
4      -61.232340
5     -354.481639
9      -37.791639
12    -403.288837
..            ...
193   -258.178837
194   -302.522340
196   -158.151639
197   -106.831639
199   -250.148837

[107 rows x 11 columns]

In [16]:
high_amount = df[df["dev_from_avg"] >  0]
print(high_amount)

      order_id customer_id  order_date region    category customer_segment  \
0    ORD_10000    CUST_131  2024-01-01   West  Technology              SMB
2    ORD_10002    CUST_117  2024-01-03   East  Technology              SMB
3    ORD_10003    CUST_106  2024-01-04   East   Furniture              SMB
6    ORD_10006    CUST_147  2024-01-07   West   Furniture       Enterprise
7    ORD_10007    CUST_109  2024-01-08  North  Technology       Enterprise
..         ...         ...         ...    ...         ...              ...
188  ORD_10188    CUST_101  2024-07-07   West  Technology       Enterprise
189  ORD_10189    CUST_125  2024-07-08  South  Technology         Consumer
190  ORD_10190    CUST_102  2024-07-09   East   Furniture       Enterprise
195  ORD_10195    CUST_129  2024-07-14  South  Technology              SMB
198  ORD_10198    CUST_142  2024-07-17  South   Furniture              SMB

     sales_amount  discount  cat_avg_sales  region_avg  dev_from_avg
0          594.27      0.05     656.324795  430.962340    163.307660
2          847.50      0.00     656.324795  413.868837    433.631163
3          560.86      0.15     357.703718  413.868837    146.991163
6          466.23      0.00     357.703718  430.962340     35.267660
7          879.11      0.00     656.324795  387.849592    491.260408
..            ...       ...            ...         ...           ...
188        877.85      0.15     656.324795  430.962340    446.887660
189        726.63      0.00     656.324795  375.271639    351.358361
190        523.78      0.00     357.703718  413.868837    109.911163
195        479.84      0.10     656.324795  375.271639    104.568361
198        502.80      0.10     357.703718  375.271639    127.528361

[93 rows x 11 columns]

In [17]:
low_amount["discount"].mean()

np.float64(0.05420560747663551)

In [18]:
high_amount["discount"].mean()

np.float64(0.05591397849462366)

In [20]:
low_amount.groupby("category").agg(sales_amount=("sales_amount", "sum"))

                 sales_amount
category
Furniture             9813.26
Office Supplies       4135.19
Technology            4524.35

In [22]:
low_amount.groupby("category").agg(Sum =("sales_amount","sum"))

                     Sum
category
Furniture        9813.26
Office Supplies  4135.19
Technology       4524.35

In [23]:
high_amount.groupby("category").agg(Sum =("sales_amount","sum"))

                 Sum
category
Furniture   18087.63
Technology  43387.36

# Pivot_table & crosstab()

In [27]:
pivot_df = pd.pivot_table(
    df,
    values="sales_amount",
    index="customer_segment",
    columns="category",
    aggfunc="mean",
    fill_value=0.0,
    margins=True
)

print(pivot_df)

category           Furniture  Office Supplies  Technology         All
customer_segment
Consumer          337.775926        81.896667  665.977692  421.817385
Enterprise        385.418182        92.366000  718.844500  496.125957
SMB               355.232414        84.081250  600.718519  331.951591
All               357.703718        84.391633  656.324795  399.738950

In [28]:
freq_table = pd.crosstab(index=df["region"],columns=df["customer_segment"],normalize="index")
print(freq_table)

customer_segment  Consumer  Enterprise       SMB
region
East              0.255814    0.395349  0.348837
North             0.326531    0.224490  0.448980
South             0.409836    0.147541  0.442623
West              0.276596    0.212766  0.510638

In [29]:
print(freq_table.round(3)*100)

customer_segment  Consumer  Enterprise   SMB
region
East                  25.6        39.5  34.9
North                 32.7        22.4  44.9
South                 41.0        14.8  44.3
West                  27.7        21.3  51.1

# Unpivot Data With melt()

In [31]:
wide_df = pd.DataFrame({
    "Product":["A","B"],
    "2024":[100,300],
    "2025":[150,350]})

long_df = pd.melt(
    wide_df, id_vars =["Product"],
    value_vars = ["2024", "2025"],
    var_name="Year",
    value_name="Sales")

print(long_df)

  Product  Year  Sales
0       A  2024    100
1       B  2024    300
2       A  2025    150
3       B  2025    350

# Statistical Insight Extraction & Outliers

In [32]:
#Coorelation Analysis
numeric_cols = df.select_dtypes("number")
print(numeric_cols.corr() ["sales_amount"])

sales_amount     1.000000
discount         0.037399
cat_avg_sales    0.739505
region_avg       0.073831
dev_from_avg     0.997271
Name: sales_amount, dtype: float64

In [33]:
Q1 = df["sales_amount"].quantile(0.25)
Q3 = df["sales_amount"].quantile(0.75)  
IQR = Q3-Q1
print(IQR)

392.7275000000001

In [35]:
lower = Q1-1.5*IQR
upper = Q3+1.5*IQR

In [36]:
outlier = df.loc[
    (df["sales_amount"] < lower) | (df["sales_amount"] > upper)]
print(f"Detected {len(outlier)} outliers")

Detected 7 outliers

In [37]:
print(outlier)

      order_id customer_id  order_date region    category customer_segment  \
29   ORD_10029    CUST_112  2024-01-30   East  Technology         Consumer
61   ORD_10061    CUST_124  2024-03-02   West  Technology         Consumer
76   ORD_10076    CUST_137  2024-03-17   West  Technology              SMB
120  ORD_10120    CUST_117  2024-04-30   West  Technology         Consumer
142  ORD_10142    CUST_149  2024-05-22   East  Technology         Consumer
144  ORD_10144    CUST_120  2024-05-24  North  Technology         Consumer
165  ORD_10165    CUST_114  2024-06-14  North  Technology       Enterprise

     sales_amount  discount  cat_avg_sales  region_avg  dev_from_avg
29        1154.10      0.10     656.324795  413.868837    740.231163
61        1132.24      0.00     656.324795  430.962340    701.277660
76        1168.42      0.00     656.324795  430.962340    737.457660
120       1181.13      0.00     656.324795  430.962340    750.167660
142       1175.96      0.20     656.324795  413.868837    762.091163
144       1153.87      0.05     656.324795  387.849592    766.020408
165       1189.68      0.10     656.324795  387.849592    801.830408

# Aggregrations (.agg())

In [24]:
#Modern Named Aggregration (.agg())
exec_summary = df.groupby("region").agg(
    total_revenue = ("sales_amount","sum"),
    avg_order_val = ("sales_amount", "mean"),
    unique_customers = ("customer_id","nunique"),
    max_discount = ("discount","max")).reset_index()
print(exec_summary)

  region  total_revenue  avg_order_val  unique_customers  max_discount
0   East       17796.36     413.868837                32           0.2
1  North       19004.63     387.849592                31           0.2
2  South       22891.57     375.271639                37           0.2
3   West       20255.23     430.962340                31           0.2

# iloc vs loc & Boolean masking

In [ ]:
#1.Label Based Slicing (.loc)
high_spenders = df.loc[df["monthly spend"] > 100.0, ["user_id", "churn_label"]]

#2. Integer Positional Slicing (.iloc) -> First 10 rows, First 3 columns
first_10_rows = df.iloc[0:10, 0:3]

# 3. Compound Boolean Logic (&,|,~)
target_cohort = df.loc[
    (df["monthly_spend"] > 50.0) & (df[

In [ ]:
# Detecting Null Patterns
#Detecting and summarizing Nulls in Pandas
print(df.isna().sum())     #per column

#Percent missing calculation
missing_pct = (df.isna().sum() / len(df)) * 100
print(missing_pct[missing_pct > 0])

# Missing Data Remediation : Deletion vs Imputation

In [ ]:
#Strategy A : Row Deletion (While missing records)
df_clean = df.dropna(subset =["user_id"])

#Strategy B : Mean & Mode Imputation
spend_median = df["monthly_spend"].median()
df["monthly_spend"] = df["monthly_spend"].fillna(spend_median)

cat_mode = df["category"].mode()[0]
df["category"] = df["category"].fillna(cat_mode)

#Strategy C: Forward Fill for Time Series/sensor Stream
df["sensor_reading"] = df["sensor_reading"].ffill().bfill()

# Data Type Casting & Memory Footprint Optimization

In [ ]:
#import pandas as pd

# Date time parsing & Date time Property Extraction
df["signup_date"] = pd.to_datetime