In [2]:
#pandas
import pandas as pd

In [48]:
df = pd.read_csv(r"C:\Users\ASUS\Desktop\DataPy\grade.csv")
df

,id,fullname,section,subject,email,marks
0,653,Nichole Carbett,D,English,ncarbett0@booking.com,78
1,680,Lonnie Slocomb,A,Multimedia,lslocomb1@arizona.edu,82
2,773,Maggee Casbourne,C,IT,mcasbourne2@yelp.com,75
3,485,Quintina Tripney,B,Multimedia,qtripney3@zdnet.com,90
4,36,Dione Dalman,D,English,ddalman4@multiply.com,90
...,...,...,...,...,...,...
145,924,Balduin Hanham,C,English,bhanham41@mail.ru,77
146,553,Dalli Jirieck,A,Multimedia,djirieck42@gnu.org,89
147,540,Paulette Rapaport,E,IT,prapaport43@usgs.gov,84
148,411,Theadora Tweed,D,Data science,ttweed44@tiny.cc,72
149,298,Malissa Daniels,D,Data science,mdaniels45@purevolume.com,96

In [5]:
pd.set_option('display.max.rows', 235)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        150 non-null    int64
 1   fullname  150 non-null    object
 2   section   150 non-null    object
 3   subject   150 non-null    object
 4   email     150 non-null    object
 5   marks     150 non-null    int64
dtypes: int64(2), object(4)
memory usage: 7.2+ KB

In [11]:
df.shape

(150, 6)

In [12]:
df.head(10)

    id          fullname section     subject                      email  marks
0  653   Nichole Carbett       D     English      ncarbett0@booking.com     78
1  680    Lonnie Slocomb       A  Multimedia      lslocomb1@arizona.edu     82
2  773  Maggee Casbourne       C          IT       mcasbourne2@yelp.com     75
3  485  Quintina Tripney       B  Multimedia        qtripney3@zdnet.com     90
4   36      Dione Dalman       D     English      ddalman4@multiply.com     90
5  669      Janessa Boik       E          IT          jboik5@toplist.cz     73
6  584  Harwell Germaine       E  Multimedia         hgermaine6@fda.gov     75
7  449       Kippy Scole       D        Math        kscole7@behance.net     77
8  856       Chan Enrich       E     English  cenrich8@chronoengine.com     87
9  266     Jesse Krammer       D  Multimedia          jkrammer9@php.net     79

In [14]:
df['marks']

0       78
1       82
2       75
3       90
4       90
5       73
6       75
7       77
8       87
9       79
10      84
11      90
12     100
13      70
14      80
15      72
16      81
17      87
18      94
19      76
20      76
21      87
22      85
23      94
24      94
25      80
26      87
27      91
28      98
29      80
30      81
31      79
32      79
33      78
34      93
35      76
36      85
37      98
38      84
39      87
40      72
41      98
42      79
43      93
44      73
45      86
46      73
47     100
48      98
49      83
50      78
51      88
52      91
53      98
54      97
55      93
56      91
57      95
58      94
59      93
60      95
61      85
62      90
63      82
64      96
65      81
66      87
67      73
68      85
69      88
70      87
71      78
72      80
73      73
74      73
75      97
76      99
77      70
78      73
79      72
80      74
81      99
82      90
83      77
84      83
85      94
86      97
87      85
88      71
89      79
90      71
91      80
92      77
93      76
94      73
95      85
96      73
97      74
98      85
99      73
100     74
101     97
102     92
103     71
104     93
105     93
106     88
107     75
108     70
109     84
110    100
111     85
112     88
113     72
114     82
115     86
116     96
117     87
118     77
119     77
120     95
121     70
122     86
123     94
124     98
125     84
126     90
127     85
128     81
129     88
130     98
131     96
132     95
133     99
134     70
135     75
136     81
137    100
138    100
139     83
140    100
141     99
142     72
143     83
144     99
145     77
146     89
147     84
148     72
149     96
Name: marks, dtype: int64

In [15]:
df.loc[105]   #index data

id                              743
fullname            Trumaine German
section                           B
subject                Data science
email       tgerman2x@over-blog.com
marks                            93
Name: 105, dtype: object

In [16]:
#iloc - integer location
df.iloc[50]

id                               993
fullname                 Berty Renol
section                            C
subject                 Data science
email       brenol1e@photobucket.com
marks                             78
Name: 50, dtype: object

In [3]:
#filtering and ordering data

df = pd.read_csv(r"C:\Users\ASUS\Desktop\DataPy\user.csv")

In [18]:
df

,id,fullname,section,subject,email,Unnamed: 5,address,gender
0,372,Astrid Spittal,B,Multimedia,aspittal0@cbsnews.com,password,Janakpur,Female
1,948,Rurik Acuna,A,Data science,racuna1@who.int,password,Lalitpur,Male
2,655,Gerhardine Lindenberg,E,Data science,glindenberg2@shinystat.com,password,Bhaktapur,Female
3,532,Bran Rands,E,Multimedia,brands3@cpanel.net,password,Gorkha,Male
4,69,Daffie Childs,C,Data science,dchilds4@furl.net,password,Kathmandu,Female
5,743,Cooper Fernihough,D,English,cfernihough5@geocities.jp,password,Gorkha,Male
6,861,Carlee Girardy,A,Multimedia,cgirardy6@vimeo.com,password,Biratnagar,Female
7,623,Marv Reder,C,English,mreder7@dmoz.org,password,Jhapa,Male
8,248,Bendicty Mordacai,C,Math,bmordacai8@canalblog.com,password,Kathmandu,Male
9,601,Andrus Cowins,B,Math,acowins9@nsw.gov.au,password,Gorkha,Polygender
10,807,Micaela De Goey,E,Multimedia,mdea@infoseek.co.jp,password,Lalitpur,Female
11,44,Dana Symes,B,IT,dsymesb@cnet.com,password,Chitwan,Male
12,328,Cassey Heugle,C,Multimedia,cheuglec@nps.gov,password,Janakpur,Female
13,670,Ric Matusiak,B,IT,rmatusiakd@etsy.com,password,Jhapa,Male
14,806,Mellisa Tomich,C,English,mtomiche@aol.com,password,Lalitpur,Female
15,598,Allina Marco,A,Data science,amarcof@yelp.com,password,Gorkha,Female
16,21,Shanta Slee,D,Math,ssleeg@php.net,password,Janakpur,Female
17,530,Alix Forrington,C,Data science,aforringtonh@pagesperso-orange.fr,password,Gorkha,Non-binary
18,258,Shannah Imeson,B,Math,simesoni@com.com,password,Jhapa,Female
19,296,Archaimbaud Kulis,D,Data science,akulisj@jiathis.com,password,Lalitpur,Male
20,321,Devinne Keedwell,D,Math,dkeedwellk@redcross.org,password,Kathmandu,Female
21,703,Raphaela Cavil,E,Math,rcavill@ask.com,password,Jhapa,Female
22,130,Gabi Bodsworth,D,English,gbodsworthm@nih.gov,password,Chitwan,Male
23,280,Brion Petyanin,B,Data science,bpetyaninn@pen.io,password,Biratnagar,Bigender
24,719,Maddy Corringham,E,IT,mcorringhamo@archive.org,password,Chitwan,Male
25,257,Marven Ducker,D,English,mduckerp@newsvine.com,password,Gorkha,Male
26,569,Hillier FitzGeorge,A,IT,hfitzgeorgeq@icq.com,password,Biratnagar,Male
27,404,Michail Bifield,D,Math,mbifieldr@zimbio.com,password,Gorkha,Male
28,654,Myer Andrichak,E,English,mandrichaks@usatoday.com,password,Chitwan,Male
29,463,Yehudit Snazel,E,IT,ysnazelt@chicagotribune.com,password,Kathmandu,Male
30,594,Hunt Harmeston,C,Multimedia,hharmestonu@reddit.com,password,Kathmandu,Male
31,454,Alasdair Padbury,B,IT,apadburyv@senate.gov,password,Bhaktapur,Male
32,819,Sella Dilke,E,Multimedia,sdilkew@guardian.co.uk,password,Kathmandu,Female
33,96,Gordy Cobbald,C,IT,gcobbaldx@forbes.com,password,Lalitpur,Agender
34,625,Sonja Nussgen,A,English,snussgeny@macromedia.com,password,Gorkha,Female
35,588,Garrick Ingleby,B,IT,ginglebyz@t-online.de,password,Gorkha,Male
36,951,Ellette Beelby,E,English,ebeelby10@ted.com,password,Gorkha,Female
37,166,Herminia Gagen,E,Multimedia,hgagen11@whitehouse.gov,password,Lalitpur,Female
38,100,Levon Agnolo,D,Math,lagnolo12@people.com.cn,password,Jhapa,Male
39,438,Dory Ferdinand,C,Data science,dferdinand13@livejournal.com,password,Janakpur,Agender
40,236,Francis Nott,B,Multimedia,fnott14@wired.com,password,Janakpur,Male
41,305,Abagail Wyllt,A,Math,awyllt15@wsj.com,password,Gorkha,Female
42,156,Minor Dibb,E,Multimedia,mdibb16@independent.co.uk,password,Jhapa,Male
43,650,Neville Ertel,E,IT,nertel17@nsw.gov.au,password,Bhaktapur,Male
44,419,Prentiss Yesson,B,Math,pyesson18@pagesperso-orange.fr,password,Bhaktapur,Male
45,389,Diahann Sherman,D,English,dsherman19@blog.com,password,Gorkha,Female
46,625,Roberta Lamberti,C,Multimedia,rlamberti1a@harvard.edu,password,Gorkha,Female
47,327,Rudolf Bewsey,A,Multimedia,rbewsey1b@youtube.com,password,Biratnagar,Male
48,328,Georgi Cradock,C,Math,gcradock1c@pbs.org,password,Biratnagar,Male
49,360,Anabella Finlater,E,Math,afinlater1d@jalbum.net,password,Bhaktapur,Female
50,378,Alexio Yakob,B,IT,ayakob1e@tinyurl.com,password,Jhapa,Male
51,566,Barthel Hars,C,Data science,bhars1f@aboutads.info,password,Chitwan,Male
52,419,Matthieu Kirsche,D,Data science,mkirsche1g@chicagotribune.com,password,Chitwan,Male
53,669,Orelia McLevie,D,Math,omclevie1h@ftc.gov,password,Gorkha,Female
54,499,Tonie Croft,E,Multimedia,tcroft1i@latimes.com,password,Chitwan,Female
55,407,Alexandra Trevers,E,English,atrevers1j@arstechnica.com,password,Chitwan,Female
56,587,Lewes Ludlow,C,English,lludlow1k@elegantthemes.com,password,Janakpur,Male
57,913,Vivi Boobier,D,English,vboobier1l@bandcamp.com,password,Jhapa,Female
58,649,Dud Muskett,B,Math,dmuskett1m@columbia.edu,password,Chitwan,Male
59,709,Laverna Drewry,E,English,ldrewry1n@timesonline.co.uk,password,Jhapa,Female
60,11,Frasco Shelsher,B,Multimedia,fshelsher1o@clickbank.net,password,Jhapa,Male
61,702,Trip O'Doherty,A,English,todoherty1p@spiegel.de,password,Biratnagar,Male
62,440,Lew Finder,D,Data science,lfinder1q@walmart.com,password,Chitwan,Male
63,295,Elnora Huonic,B,Data science,ehuonic1r@theguardian.com,password,Biratnagar,Female
64,442,Patricia Loughlan,C,Multimedia,ploughlan1s@twitter.com,password,Gorkha,Agender
65,395,Madelin Theakston,D,Math,mtheakston1t@tmall.com,password,Biratnagar,Female
66,527,Courtney Leathers,C,Data science,cleathers1u@dedecms.com,password,Biratnagar,Female
67,515,Irina Lowth,A,IT,ilowth1v@free.fr,password,Lalitpur,Agender
68,112,Basilius Ramsier,B,IT,bramsier1w@springer.com,password,Bhaktapur,Male
69,358,Brunhilde Alliberton,C,IT,balliberton1x@feedburner.com,password,Kathmandu,Female
70,983,Pedro Vlasin,A,IT,pvlasin1y@wikimedia.org,password,Biratnagar,Male
71,601,Aarika Peacher,B,Multimedia,apeacher1z@yandex.ru,password,Jhapa,Female
72,746,Emma Piele,A,Math,epiele20@dailymotion.com,password,Lalitpur,Female
73,696,Reinaldo Fairbank,D,Multimedia,rfairbank21@europa.eu,password,Biratnagar,Male
74,513,Rosina Laver,D,English,rlaver22@sfgate.com,password,Janakpur,Female
75,303,Alikee Brewis,B,Multimedia,abrewis23@paypal.com,password,Chitwan,Female
76,274,Calypso Casley,A,English,ccasley24@networksolutions.com,password,Janakpur,Female
77,799,Caitlin Render,D,Multimedia,crender25@cam.ac.uk,password,Jhapa,Female
78,41,Boonie Gratten,E,Multimedia,bgratten26@japanpost.jp,password,Chitwan,Male
79,358,Jacquelin Kohlerman,C,IT,jkohlerman27@tripadvisor.com,password,Bhaktapur,Female
80,442,Sinclair Calleja,B,Math,scalleja28@msu.edu,password,Lalitpur,Male
81,893,Warde Ferreira,C,English,wferreira29@hexun.com,password,Jhapa,Male
82,884,Ozzie Hugo,C,Multimedia,ohugo2a@drupal.org,password,Kathmandu,Male
83,64,Omar Pinnick,A,Multimedia,opinnick2b@digg.com,password,Janakpur,Male
84,13,Evelina Eady,A,Data science,eeady2c@geocities.com,password,Gorkha,Female
85,509,Orly Trahar,C,Multimedia,otrahar2d@altervista.org,password,Jhapa,Polygender
86,884,Mychal Legister,B,Data science,mlegister2e@shop-pro.jp,password,Lalitpur,Male
87,850,Cortney Koba,A,Math,ckoba2f@ycombinator.com,password,Kathmandu,Female
88,964,Maggee Dudney,E,IT,mdudney2g@icio.us,password,Chitwan,Female
89,913,Jabez Moryson,C,Multimedia,jmoryson2h@sphinn.com,password,Bhaktapur,Male
90,445,Em Findlow,B,IT,efindlow2i@shop-pro.jp,password,Janakpur,Female
91,940,Maureene Postles,D,English,mpostles2j@discuz.net,password,Biratnagar,Female
92,931,Judd Tukesby,D,Data science,jtukesby2k@joomla.org,password,Chitwan,Non-binary
93,121,Phineas Seywood,D,Math,pseywood2l@slideshare.net,password,Lalitpur,Male
94,273,Charlean Dumbell,D,English,cdumbell2m@eepurl.com,password,Gorkha,Non-binary
95,555,Kenyon Giorgi,A,Data science,kgiorgi2n@de.vu,password,Gorkha,Polygender
96,332,Thomasin Longcake,C,Math,tlongcake2o@amazon.de,password,Biratnagar,Female
97,348,Zacherie Usher,C,English,zusher2p@cdbaby.com,password,Biratnagar,Male
98,234,Ethe Bengle,B,English,ebengle2q@washingtonpost.com,password,Biratnagar,Male
99,155,Xerxes Compfort,D,IT,xcompfort2r@t-online.de,password,Bhaktapur,Male
100,607,Amby Walisiak,C,Data science,awalisiak2s@is.gd,password,Chitwan,Male
101,289,Bekki Glas,B,Multimedia,bglas2t@com.com,password,Kathmandu,Bigender
102,92,Claudell Farnan,B,English,cfarnan2u@engadget.com,password,Gorkha,Male
103,500,Evania Pithie,E,Multimedia,epithie2v@yellowpages.com,password,Jhapa,Female
104,406,Una Amps,A,IT,uamps2w@taobao.com,password,Janakpur,Female
105,92,Melvin Wheelan,E,Data science,mwheelan2x@technorati.com,password,Biratnagar,Male
106,898,Gasparo Abberley,D,Data science,gabberley2y@cpanel.net,password,Biratnagar,Male
107,909,Melodee Guye,E,Data science,mguye2z@cdbaby.com,password,Chitwan,Female
108,108,Evangeline Oxbrow,B,IT,eoxbrow30@yahoo.com,password,Janakpur,Female
109,826,Milo Amort,E,Math,mamort31@hibu.com,password,Chitwan,Male
110,16,Serge Reap,C,Data science,sreap32@ft.com,password,Gorkha,Male
111,210,Wilfred Tweede,E,English,wtweede33@e-recht24.de,password,Gorkha,Male
112,702,Adrianne Meaden,A,English,ameaden34@comcast.net,password,Jhapa,Female
113,845,Sarene Vurley,A,Math,svurley35@zimbio.com,password,Chitwan,Female
114,645,Enrico Eakley,C,Data science,eeakley36@craigslist.org,password,Kathmandu,Male
115,223,Carlin Demicoli,E,Multimedia,cdemicoli37@squarespace.com,password,Chitwan,Male
116,534,Fallon Attle,C,IT,fattle38@delicious.com,password,Biratnagar,Genderqueer
117,298,Henka Creighton,D,Math,hcreighton39@psu.edu,password,Lalitpur,Female
118,832,Doyle Thrasher,C,Data science,dthrasher3a@pagesperso-orange.fr,password,Gorkha,Male
119,461,Teddie Smewing,B,Multimedia,tsmewing3b@t-online.de,password,Kathmandu,Female
120,826,Egon Ferryn,B,Multimedia,eferryn3c@weibo.com,password,Janakpur,Male
121,329,Jeremiah Lednor,C,Multimedia,jlednor3d@liveinternet.ru,password,Kathmandu,Male
122,573,Truda Coppen,E,Data science,tcoppen3e@marriott.com,password,Janakpur,Female
123,291,Carlynne Pilsworth,E,IT,cpilsworth3f@amazonaws.com,password,Jhapa,Female
124,955,Jaquenetta Attenbarrow,D,Data science,jattenbarrow3g@samsung.com,password,Chitwan,Female
125,746,Bunny Furmonger,B,English,bfurmonger3h@wp.com,password,Kathmandu,Female
126,203,Filberte Dranfield,D,IT,fdranfield3i@infoseek.co.jp,password,Jhapa,Male
127,776,Wilie Trowell,E,English,wtrowell3j@eepurl.com,password,Kathmandu,Genderfluid
128,692,Cullie Gilleson,C,Data science,cgilleson3k@nasa.gov,password,Jhapa,Male
129,287,Janella Pighills,B,Data science,jpighills3l@stanford.edu,password,Biratnagar,Female
130,199,Hobie Haggerston,D,Multimedia,hhaggerston3m@nih.gov,password,Biratnagar,Non-binary
131,60,Barry Dumphy,A,Data science,bdumphy3n@xing.com,password,Chitwan,Male
132,736,Brandi Blackwood,E,IT,bblackwood3o@spotify.com,password,Biratnagar,Female
133,34,Tomas L' Estrange,D,Multimedia,tl3p@wikispaces.com,password,Lalitpur,Male
134,743,Philly MacKinnon,C,Math,pmackinnon3q@hostgator.com,password,Gorkha,Female
135,50,Kalila Keningley,C,Math,kkeningley3r@bravesites.com,password,Chitwan,Female
136,295,Bryanty Oulet,B,IT,boulet3s@imageshack.us,password,Janakpur,Male
137,506,Mayor Poynter,B,IT,mpoynter3t@posterous.com,password,Kathmandu,Male
138,756,Wilburt Pestricke,B,Data science,wpestricke3u@seattletimes.com,password,Gorkha,Male
139,195,Rheba Dennehy,A,Multimedia,rdennehy3v@ox.ac.uk,password,Gorkha,Female
140,349,Hakim Bottomley,B,IT,hbottomley3w@indiegogo.com,password,Gorkha,Male
141,965,Far Molineaux,E,English,fmolineaux3x@dedecms.com,password,Bhaktapur,Male
142,635,Gladi Ickovic,B,IT,gickovic3y@trellian.com,password,Janakpur,Female
143,932,Dory Kardos,A,Multimedia,dkardos3z@washingtonpost.com,password,Biratnagar,Female
144,112,Carmel Lindfors,A,English,clindfors40@icio.us,password,Bhaktapur,Female
145,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Janakpur,Bigender
146,515,Andi Smethurst,C,Math,asmethurst42@sun.com,password,Bhaktapur,Female
147,640,Clarissa Drinkale,C,Multimedia,cdrinkale43@nifty.com,password,Bhaktapur,Female
148,986,Rubetta Barrass,D,Multimedia,rbarrass44@blogtalkradio.com,password,Janakpur,Female
149,740,Zonda Adnett,A,Data science,zadnett45@shinystat.com,password,Gorkha,Female

In [4]:
df[df['id'] < 10]

,id,fullname,section,subject,email,Unnamed: 5,address,gender
145,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Janakpur,Bigender

In [20]:
specific_address = ['Janakpur', 'Kathmandu' ]

In [21]:
df[df['address'].isin(specific_address)]

,id,fullname,section,subject,email,Unnamed: 5,address,gender
0,372,Astrid Spittal,B,Multimedia,aspittal0@cbsnews.com,password,Janakpur,Female
4,69,Daffie Childs,C,Data science,dchilds4@furl.net,password,Kathmandu,Female
8,248,Bendicty Mordacai,C,Math,bmordacai8@canalblog.com,password,Kathmandu,Male
12,328,Cassey Heugle,C,Multimedia,cheuglec@nps.gov,password,Janakpur,Female
16,21,Shanta Slee,D,Math,ssleeg@php.net,password,Janakpur,Female
20,321,Devinne Keedwell,D,Math,dkeedwellk@redcross.org,password,Kathmandu,Female
29,463,Yehudit Snazel,E,IT,ysnazelt@chicagotribune.com,password,Kathmandu,Male
30,594,Hunt Harmeston,C,Multimedia,hharmestonu@reddit.com,password,Kathmandu,Male
32,819,Sella Dilke,E,Multimedia,sdilkew@guardian.co.uk,password,Kathmandu,Female
39,438,Dory Ferdinand,C,Data science,dferdinand13@livejournal.com,password,Janakpur,Agender
40,236,Francis Nott,B,Multimedia,fnott14@wired.com,password,Janakpur,Male
56,587,Lewes Ludlow,C,English,lludlow1k@elegantthemes.com,password,Janakpur,Male
69,358,Brunhilde Alliberton,C,IT,balliberton1x@feedburner.com,password,Kathmandu,Female
74,513,Rosina Laver,D,English,rlaver22@sfgate.com,password,Janakpur,Female
76,274,Calypso Casley,A,English,ccasley24@networksolutions.com,password,Janakpur,Female
82,884,Ozzie Hugo,C,Multimedia,ohugo2a@drupal.org,password,Kathmandu,Male
83,64,Omar Pinnick,A,Multimedia,opinnick2b@digg.com,password,Janakpur,Male
87,850,Cortney Koba,A,Math,ckoba2f@ycombinator.com,password,Kathmandu,Female
90,445,Em Findlow,B,IT,efindlow2i@shop-pro.jp,password,Janakpur,Female
101,289,Bekki Glas,B,Multimedia,bglas2t@com.com,password,Kathmandu,Bigender
104,406,Una Amps,A,IT,uamps2w@taobao.com,password,Janakpur,Female
108,108,Evangeline Oxbrow,B,IT,eoxbrow30@yahoo.com,password,Janakpur,Female
114,645,Enrico Eakley,C,Data science,eeakley36@craigslist.org,password,Kathmandu,Male
119,461,Teddie Smewing,B,Multimedia,tsmewing3b@t-online.de,password,Kathmandu,Female
120,826,Egon Ferryn,B,Multimedia,eferryn3c@weibo.com,password,Janakpur,Male
121,329,Jeremiah Lednor,C,Multimedia,jlednor3d@liveinternet.ru,password,Kathmandu,Male
122,573,Truda Coppen,E,Data science,tcoppen3e@marriott.com,password,Janakpur,Female
125,746,Bunny Furmonger,B,English,bfurmonger3h@wp.com,password,Kathmandu,Female
127,776,Wilie Trowell,E,English,wtrowell3j@eepurl.com,password,Kathmandu,Genderfluid
136,295,Bryanty Oulet,B,IT,boulet3s@imageshack.us,password,Janakpur,Male
137,506,Mayor Poynter,B,IT,mpoynter3t@posterous.com,password,Kathmandu,Male
142,635,Gladi Ickovic,B,IT,gickovic3y@trellian.com,password,Janakpur,Female
145,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Janakpur,Bigender
148,986,Rubetta Barrass,D,Multimedia,rbarrass44@blogtalkradio.com,password,Janakpur,Female

In [22]:
df[df['address'].str.contains('Gorkha')]

,id,fullname,section,subject,email,Unnamed: 5,address,gender
3,532,Bran Rands,E,Multimedia,brands3@cpanel.net,password,Gorkha,Male
5,743,Cooper Fernihough,D,English,cfernihough5@geocities.jp,password,Gorkha,Male
9,601,Andrus Cowins,B,Math,acowins9@nsw.gov.au,password,Gorkha,Polygender
15,598,Allina Marco,A,Data science,amarcof@yelp.com,password,Gorkha,Female
17,530,Alix Forrington,C,Data science,aforringtonh@pagesperso-orange.fr,password,Gorkha,Non-binary
25,257,Marven Ducker,D,English,mduckerp@newsvine.com,password,Gorkha,Male
27,404,Michail Bifield,D,Math,mbifieldr@zimbio.com,password,Gorkha,Male
34,625,Sonja Nussgen,A,English,snussgeny@macromedia.com,password,Gorkha,Female
35,588,Garrick Ingleby,B,IT,ginglebyz@t-online.de,password,Gorkha,Male
36,951,Ellette Beelby,E,English,ebeelby10@ted.com,password,Gorkha,Female
41,305,Abagail Wyllt,A,Math,awyllt15@wsj.com,password,Gorkha,Female
45,389,Diahann Sherman,D,English,dsherman19@blog.com,password,Gorkha,Female
46,625,Roberta Lamberti,C,Multimedia,rlamberti1a@harvard.edu,password,Gorkha,Female
53,669,Orelia McLevie,D,Math,omclevie1h@ftc.gov,password,Gorkha,Female
64,442,Patricia Loughlan,C,Multimedia,ploughlan1s@twitter.com,password,Gorkha,Agender
84,13,Evelina Eady,A,Data science,eeady2c@geocities.com,password,Gorkha,Female
94,273,Charlean Dumbell,D,English,cdumbell2m@eepurl.com,password,Gorkha,Non-binary
95,555,Kenyon Giorgi,A,Data science,kgiorgi2n@de.vu,password,Gorkha,Polygender
102,92,Claudell Farnan,B,English,cfarnan2u@engadget.com,password,Gorkha,Male
110,16,Serge Reap,C,Data science,sreap32@ft.com,password,Gorkha,Male
111,210,Wilfred Tweede,E,English,wtweede33@e-recht24.de,password,Gorkha,Male
118,832,Doyle Thrasher,C,Data science,dthrasher3a@pagesperso-orange.fr,password,Gorkha,Male
134,743,Philly MacKinnon,C,Math,pmackinnon3q@hostgator.com,password,Gorkha,Female
138,756,Wilburt Pestricke,B,Data science,wpestricke3u@seattletimes.com,password,Gorkha,Male
139,195,Rheba Dennehy,A,Multimedia,rdennehy3v@ox.ac.uk,password,Gorkha,Female
140,349,Hakim Bottomley,B,IT,hbottomley3w@indiegogo.com,password,Gorkha,Male
149,740,Zonda Adnett,A,Data science,zadnett45@shinystat.com,password,Gorkha,Female

In [23]:
df = df.set_index("address")
df

,id,fullname,section,subject,email,Unnamed: 5,gender
address,,,,,,,
Janakpur,372,Astrid Spittal,B,Multimedia,aspittal0@cbsnews.com,password,Female
Lalitpur,948,Rurik Acuna,A,Data science,racuna1@who.int,password,Male
Bhaktapur,655,Gerhardine Lindenberg,E,Data science,glindenberg2@shinystat.com,password,Female
Gorkha,532,Bran Rands,E,Multimedia,brands3@cpanel.net,password,Male
Kathmandu,69,Daffie Childs,C,Data science,dchilds4@furl.net,password,Female
Gorkha,743,Cooper Fernihough,D,English,cfernihough5@geocities.jp,password,Male
Biratnagar,861,Carlee Girardy,A,Multimedia,cgirardy6@vimeo.com,password,Female
Jhapa,623,Marv Reder,C,English,mreder7@dmoz.org,password,Male
Kathmandu,248,Bendicty Mordacai,C,Math,bmordacai8@canalblog.com,password,Male
Gorkha,601,Andrus Cowins,B,Math,acowins9@nsw.gov.au,password,Polygender
Lalitpur,807,Micaela De Goey,E,Multimedia,mdea@infoseek.co.jp,password,Female
Chitwan,44,Dana Symes,B,IT,dsymesb@cnet.com,password,Male
Janakpur,328,Cassey Heugle,C,Multimedia,cheuglec@nps.gov,password,Female
Jhapa,670,Ric Matusiak,B,IT,rmatusiakd@etsy.com,password,Male
Lalitpur,806,Mellisa Tomich,C,English,mtomiche@aol.com,password,Female
Gorkha,598,Allina Marco,A,Data science,amarcof@yelp.com,password,Female
Janakpur,21,Shanta Slee,D,Math,ssleeg@php.net,password,Female
Gorkha,530,Alix Forrington,C,Data science,aforringtonh@pagesperso-orange.fr,password,Non-binary
Jhapa,258,Shannah Imeson,B,Math,simesoni@com.com,password,Female
Lalitpur,296,Archaimbaud Kulis,D,Data science,akulisj@jiathis.com,password,Male
Kathmandu,321,Devinne Keedwell,D,Math,dkeedwellk@redcross.org,password,Female
Jhapa,703,Raphaela Cavil,E,Math,rcavill@ask.com,password,Female
Chitwan,130,Gabi Bodsworth,D,English,gbodsworthm@nih.gov,password,Male
Biratnagar,280,Brion Petyanin,B,Data science,bpetyaninn@pen.io,password,Bigender
Chitwan,719,Maddy Corringham,E,IT,mcorringhamo@archive.org,password,Male
Gorkha,257,Marven Ducker,D,English,mduckerp@newsvine.com,password,Male
Biratnagar,569,Hillier FitzGeorge,A,IT,hfitzgeorgeq@icq.com,password,Male
Gorkha,404,Michail Bifield,D,Math,mbifieldr@zimbio.com,password,Male
Chitwan,654,Myer Andrichak,E,English,mandrichaks@usatoday.com,password,Male
Kathmandu,463,Yehudit Snazel,E,IT,ysnazelt@chicagotribune.com,password,Male
Kathmandu,594,Hunt Harmeston,C,Multimedia,hharmestonu@reddit.com,password,Male
Bhaktapur,454,Alasdair Padbury,B,IT,apadburyv@senate.gov,password,Male
Kathmandu,819,Sella Dilke,E,Multimedia,sdilkew@guardian.co.uk,password,Female
Lalitpur,96,Gordy Cobbald,C,IT,gcobbaldx@forbes.com,password,Agender
Gorkha,625,Sonja Nussgen,A,English,snussgeny@macromedia.com,password,Female
Gorkha,588,Garrick Ingleby,B,IT,ginglebyz@t-online.de,password,Male
Gorkha,951,Ellette Beelby,E,English,ebeelby10@ted.com,password,Female
Lalitpur,166,Herminia Gagen,E,Multimedia,hgagen11@whitehouse.gov,password,Female
Jhapa,100,Levon Agnolo,D,Math,lagnolo12@people.com.cn,password,Male
Janakpur,438,Dory Ferdinand,C,Data science,dferdinand13@livejournal.com,password,Agender
Janakpur,236,Francis Nott,B,Multimedia,fnott14@wired.com,password,Male
Gorkha,305,Abagail Wyllt,A,Math,awyllt15@wsj.com,password,Female
Jhapa,156,Minor Dibb,E,Multimedia,mdibb16@independent.co.uk,password,Male
Bhaktapur,650,Neville Ertel,E,IT,nertel17@nsw.gov.au,password,Male
Bhaktapur,419,Prentiss Yesson,B,Math,pyesson18@pagesperso-orange.fr,password,Male
Gorkha,389,Diahann Sherman,D,English,dsherman19@blog.com,password,Female
Gorkha,625,Roberta Lamberti,C,Multimedia,rlamberti1a@harvard.edu,password,Female
Biratnagar,327,Rudolf Bewsey,A,Multimedia,rbewsey1b@youtube.com,password,Male
Biratnagar,328,Georgi Cradock,C,Math,gcradock1c@pbs.org,password,Male
Bhaktapur,360,Anabella Finlater,E,Math,afinlater1d@jalbum.net,password,Female
Jhapa,378,Alexio Yakob,B,IT,ayakob1e@tinyurl.com,password,Male
Chitwan,566,Barthel Hars,C,Data science,bhars1f@aboutads.info,password,Male
Chitwan,419,Matthieu Kirsche,D,Data science,mkirsche1g@chicagotribune.com,password,Male
Gorkha,669,Orelia McLevie,D,Math,omclevie1h@ftc.gov,password,Female
Chitwan,499,Tonie Croft,E,Multimedia,tcroft1i@latimes.com,password,Female
Chitwan,407,Alexandra Trevers,E,English,atrevers1j@arstechnica.com,password,Female
Janakpur,587,Lewes Ludlow,C,English,lludlow1k@elegantthemes.com,password,Male
Jhapa,913,Vivi Boobier,D,English,vboobier1l@bandcamp.com,password,Female
Chitwan,649,Dud Muskett,B,Math,dmuskett1m@columbia.edu,password,Male
Jhapa,709,Laverna Drewry,E,English,ldrewry1n@timesonline.co.uk,password,Female
Jhapa,11,Frasco Shelsher,B,Multimedia,fshelsher1o@clickbank.net,password,Male
Biratnagar,702,Trip O'Doherty,A,English,todoherty1p@spiegel.de,password,Male
Chitwan,440,Lew Finder,D,Data science,lfinder1q@walmart.com,password,Male
Biratnagar,295,Elnora Huonic,B,Data science,ehuonic1r@theguardian.com,password,Female
Gorkha,442,Patricia Loughlan,C,Multimedia,ploughlan1s@twitter.com,password,Agender
Biratnagar,395,Madelin Theakston,D,Math,mtheakston1t@tmall.com,password,Female
Biratnagar,527,Courtney Leathers,C,Data science,cleathers1u@dedecms.com,password,Female
Lalitpur,515,Irina Lowth,A,IT,ilowth1v@free.fr,password,Agender
Bhaktapur,112,Basilius Ramsier,B,IT,bramsier1w@springer.com,password,Male
Kathmandu,358,Brunhilde Alliberton,C,IT,balliberton1x@feedburner.com,password,Female
Biratnagar,983,Pedro Vlasin,A,IT,pvlasin1y@wikimedia.org,password,Male
Jhapa,601,Aarika Peacher,B,Multimedia,apeacher1z@yandex.ru,password,Female
Lalitpur,746,Emma Piele,A,Math,epiele20@dailymotion.com,password,Female
Biratnagar,696,Reinaldo Fairbank,D,Multimedia,rfairbank21@europa.eu,password,Male
Janakpur,513,Rosina Laver,D,English,rlaver22@sfgate.com,password,Female
Chitwan,303,Alikee Brewis,B,Multimedia,abrewis23@paypal.com,password,Female
Janakpur,274,Calypso Casley,A,English,ccasley24@networksolutions.com,password,Female
Jhapa,799,Caitlin Render,D,Multimedia,crender25@cam.ac.uk,password,Female
Chitwan,41,Boonie Gratten,E,Multimedia,bgratten26@japanpost.jp,password,Male
Bhaktapur,358,Jacquelin Kohlerman,C,IT,jkohlerman27@tripadvisor.com,password,Female
Lalitpur,442,Sinclair Calleja,B,Math,scalleja28@msu.edu,password,Male
Jhapa,893,Warde Ferreira,C,English,wferreira29@hexun.com,password,Male
Kathmandu,884,Ozzie Hugo,C,Multimedia,ohugo2a@drupal.org,password,Male
Janakpur,64,Omar Pinnick,A,Multimedia,opinnick2b@digg.com,password,Male
Gorkha,13,Evelina Eady,A,Data science,eeady2c@geocities.com,password,Female
Jhapa,509,Orly Trahar,C,Multimedia,otrahar2d@altervista.org,password,Polygender
Lalitpur,884,Mychal Legister,B,Data science,mlegister2e@shop-pro.jp,password,Male
Kathmandu,850,Cortney Koba,A,Math,ckoba2f@ycombinator.com,password,Female
Chitwan,964,Maggee Dudney,E,IT,mdudney2g@icio.us,password,Female
Bhaktapur,913,Jabez Moryson,C,Multimedia,jmoryson2h@sphinn.com,password,Male
Janakpur,445,Em Findlow,B,IT,efindlow2i@shop-pro.jp,password,Female
Biratnagar,940,Maureene Postles,D,English,mpostles2j@discuz.net,password,Female
Chitwan,931,Judd Tukesby,D,Data science,jtukesby2k@joomla.org,password,Non-binary
Lalitpur,121,Phineas Seywood,D,Math,pseywood2l@slideshare.net,password,Male
Gorkha,273,Charlean Dumbell,D,English,cdumbell2m@eepurl.com,password,Non-binary
Gorkha,555,Kenyon Giorgi,A,Data science,kgiorgi2n@de.vu,password,Polygender
Biratnagar,332,Thomasin Longcake,C,Math,tlongcake2o@amazon.de,password,Female
Biratnagar,348,Zacherie Usher,C,English,zusher2p@cdbaby.com,password,Male
Biratnagar,234,Ethe Bengle,B,English,ebengle2q@washingtonpost.com,password,Male
Bhaktapur,155,Xerxes Compfort,D,IT,xcompfort2r@t-online.de,password,Male
Chitwan,607,Amby Walisiak,C,Data science,awalisiak2s@is.gd,password,Male
Kathmandu,289,Bekki Glas,B,Multimedia,bglas2t@com.com,password,Bigender
Gorkha,92,Claudell Farnan,B,English,cfarnan2u@engadget.com,password,Male
Jhapa,500,Evania Pithie,E,Multimedia,epithie2v@yellowpages.com,password,Female
Janakpur,406,Una Amps,A,IT,uamps2w@taobao.com,password,Female
Biratnagar,92,Melvin Wheelan,E,Data science,mwheelan2x@technorati.com,password,Male
Biratnagar,898,Gasparo Abberley,D,Data science,gabberley2y@cpanel.net,password,Male
Chitwan,909,Melodee Guye,E,Data science,mguye2z@cdbaby.com,password,Female
Janakpur,108,Evangeline Oxbrow,B,IT,eoxbrow30@yahoo.com,password,Female
Chitwan,826,Milo Amort,E,Math,mamort31@hibu.com,password,Male
Gorkha,16,Serge Reap,C,Data science,sreap32@ft.com,password,Male
Gorkha,210,Wilfred Tweede,E,English,wtweede33@e-recht24.de,password,Male
Jhapa,702,Adrianne Meaden,A,English,ameaden34@comcast.net,password,Female
Chitwan,845,Sarene Vurley,A,Math,svurley35@zimbio.com,password,Female
Kathmandu,645,Enrico Eakley,C,Data science,eeakley36@craigslist.org,password,Male
Chitwan,223,Carlin Demicoli,E,Multimedia,cdemicoli37@squarespace.com,password,Male
Biratnagar,534,Fallon Attle,C,IT,fattle38@delicious.com,password,Genderqueer
Lalitpur,298,Henka Creighton,D,Math,hcreighton39@psu.edu,password,Female
Gorkha,832,Doyle Thrasher,C,Data science,dthrasher3a@pagesperso-orange.fr,password,Male
Kathmandu,461,Teddie Smewing,B,Multimedia,tsmewing3b@t-online.de,password,Female
Janakpur,826,Egon Ferryn,B,Multimedia,eferryn3c@weibo.com,password,Male
Kathmandu,329,Jeremiah Lednor,C,Multimedia,jlednor3d@liveinternet.ru,password,Male
Janakpur,573,Truda Coppen,E,Data science,tcoppen3e@marriott.com,password,Female
Jhapa,291,Carlynne Pilsworth,E,IT,cpilsworth3f@amazonaws.com,password,Female
Chitwan,955,Jaquenetta Attenbarrow,D,Data science,jattenbarrow3g@samsung.com,password,Female
Kathmandu,746,Bunny Furmonger,B,English,bfurmonger3h@wp.com,password,Female
Jhapa,203,Filberte Dranfield,D,IT,fdranfield3i@infoseek.co.jp,password,Male
Kathmandu,776,Wilie Trowell,E,English,wtrowell3j@eepurl.com,password,Genderfluid
Jhapa,692,Cullie Gilleson,C,Data science,cgilleson3k@nasa.gov,password,Male
Biratnagar,287,Janella Pighills,B,Data science,jpighills3l@stanford.edu,password,Female
Biratnagar,199,Hobie Haggerston,D,Multimedia,hhaggerston3m@nih.gov,password,Non-binary
Chitwan,60,Barry Dumphy,A,Data science,bdumphy3n@xing.com,password,Male
Biratnagar,736,Brandi Blackwood,E,IT,bblackwood3o@spotify.com,password,Female
Lalitpur,34,Tomas L' Estrange,D,Multimedia,tl3p@wikispaces.com,password,Male
Gorkha,743,Philly MacKinnon,C,Math,pmackinnon3q@hostgator.com,password,Female
Chitwan,50,Kalila Keningley,C,Math,kkeningley3r@bravesites.com,password,Female
Janakpur,295,Bryanty Oulet,B,IT,boulet3s@imageshack.us,password,Male
Kathmandu,506,Mayor Poynter,B,IT,mpoynter3t@posterous.com,password,Male
Gorkha,756,Wilburt Pestricke,B,Data science,wpestricke3u@seattletimes.com,password,Male
Gorkha,195,Rheba Dennehy,A,Multimedia,rdennehy3v@ox.ac.uk,password,Female
Gorkha,349,Hakim Bottomley,B,IT,hbottomley3w@indiegogo.com,password,Male
Bhaktapur,965,Far Molineaux,E,English,fmolineaux3x@dedecms.com,password,Male
Janakpur,635,Gladi Ickovic,B,IT,gickovic3y@trellian.com,password,Female
Biratnagar,932,Dory Kardos,A,Multimedia,dkardos3z@washingtonpost.com,password,Female
Bhaktapur,112,Carmel Lindfors,A,English,clindfors40@icio.us,password,Female
Janakpur,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Bigender
Bhaktapur,515,Andi Smethurst,C,Math,asmethurst42@sun.com,password,Female
Bhaktapur,640,Clarissa Drinkale,C,Multimedia,cdrinkale43@nifty.com,password,Female
Janakpur,986,Rubetta Barrass,D,Multimedia,rbarrass44@blogtalkradio.com,password,Female
Gorkha,740,Zonda Adnett,A,Data science,zadnett45@shinystat.com,password,Female

In [24]:
df.filter(items = ['subject','gender'], axis = 1)

                 subject       gender
address
Janakpur      Multimedia       Female
Lalitpur    Data science         Male
Bhaktapur   Data science       Female
Gorkha        Multimedia         Male
Kathmandu   Data science       Female
Gorkha           English         Male
Biratnagar    Multimedia       Female
Jhapa            English         Male
Kathmandu           Math         Male
Gorkha              Math   Polygender
Lalitpur      Multimedia       Female
Chitwan               IT         Male
Janakpur      Multimedia       Female
Jhapa                 IT         Male
Lalitpur         English       Female
Gorkha      Data science       Female
Janakpur            Math       Female
Gorkha      Data science   Non-binary
Jhapa               Math       Female
Lalitpur    Data science         Male
Kathmandu           Math       Female
Jhapa               Math       Female
Chitwan          English         Male
Biratnagar  Data science     Bigender
Chitwan               IT         Male
Gorkha           English         Male
Biratnagar            IT         Male
Gorkha              Math         Male
Chitwan          English         Male
Kathmandu             IT         Male
Kathmandu     Multimedia         Male
Bhaktapur             IT         Male
Kathmandu     Multimedia       Female
Lalitpur              IT      Agender
Gorkha           English       Female
Gorkha                IT         Male
Gorkha           English       Female
Lalitpur      Multimedia       Female
Jhapa               Math         Male
Janakpur    Data science      Agender
Janakpur      Multimedia         Male
Gorkha              Math       Female
Jhapa         Multimedia         Male
Bhaktapur             IT         Male
Bhaktapur           Math         Male
Gorkha           English       Female
Gorkha        Multimedia       Female
Biratnagar    Multimedia         Male
Biratnagar          Math         Male
Bhaktapur           Math       Female
Jhapa                 IT         Male
Chitwan     Data science         Male
Chitwan     Data science         Male
Gorkha              Math       Female
Chitwan       Multimedia       Female
Chitwan          English       Female
Janakpur         English         Male
Jhapa            English       Female
Chitwan             Math         Male
Jhapa            English       Female
Jhapa         Multimedia         Male
Biratnagar       English         Male
Chitwan     Data science         Male
Biratnagar  Data science       Female
Gorkha        Multimedia      Agender
Biratnagar          Math       Female
Biratnagar  Data science       Female
Lalitpur              IT      Agender
Bhaktapur             IT         Male
Kathmandu             IT       Female
Biratnagar            IT         Male
Jhapa         Multimedia       Female
Lalitpur            Math       Female
Biratnagar    Multimedia         Male
Janakpur         English       Female
Chitwan       Multimedia       Female
Janakpur         English       Female
Jhapa         Multimedia       Female
Chitwan       Multimedia         Male
Bhaktapur             IT       Female
Lalitpur            Math         Male
Jhapa            English         Male
Kathmandu     Multimedia         Male
Janakpur      Multimedia         Male
Gorkha      Data science       Female
Jhapa         Multimedia   Polygender
Lalitpur    Data science         Male
Kathmandu           Math       Female
Chitwan               IT       Female
Bhaktapur     Multimedia         Male
Janakpur              IT       Female
Biratnagar       English       Female
Chitwan     Data science   Non-binary
Lalitpur            Math         Male
Gorkha           English   Non-binary
Gorkha      Data science   Polygender
Biratnagar          Math       Female
Biratnagar       English         Male
Biratnagar       English         Male
Bhaktapur             IT         Male
Chitwan     Data science         Male
Kathmandu     Multimedia     Bigender
Gorkha           English         Male
Jhapa         Multimedia       Female
Janakpur              IT       Female
Biratnagar  Data science         Male
Biratnagar  Data science         Male
Chitwan     Data science       Female
Janakpur              IT       Female
Chitwan             Math         Male
Gorkha      Data science         Male
Gorkha           English         Male
Jhapa            English       Female
Chitwan             Math       Female
Kathmandu   Data science         Male
Chitwan       Multimedia         Male
Biratnagar            IT  Genderqueer
Lalitpur            Math       Female
Gorkha      Data science         Male
Kathmandu     Multimedia       Female
Janakpur      Multimedia         Male
Kathmandu     Multimedia         Male
Janakpur    Data science       Female
Jhapa                 IT       Female
Chitwan     Data science       Female
Kathmandu        English       Female
Jhapa                 IT         Male
Kathmandu        English  Genderfluid
Jhapa       Data science         Male
Biratnagar  Data science       Female
Biratnagar    Multimedia   Non-binary
Chitwan     Data science         Male
Biratnagar            IT       Female
Lalitpur      Multimedia         Male
Gorkha              Math       Female
Chitwan             Math       Female
Janakpur              IT         Male
Kathmandu             IT         Male
Gorkha      Data science         Male
Gorkha        Multimedia       Female
Gorkha                IT         Male
Bhaktapur        English         Male
Janakpur              IT       Female
Biratnagar    Multimedia       Female
Bhaktapur        English       Female
Janakpur      Multimedia     Bigender
Bhaktapur           Math       Female
Bhaktapur     Multimedia       Female
Janakpur      Multimedia       Female
Gorkha      Data science       Female

In [25]:
df.filter(items = ['subject','gender'], axis = 1)

                 subject       gender
address
Janakpur      Multimedia       Female
Lalitpur    Data science         Male
Bhaktapur   Data science       Female
Gorkha        Multimedia         Male
Kathmandu   Data science       Female
Gorkha           English         Male
Biratnagar    Multimedia       Female
Jhapa            English         Male
Kathmandu           Math         Male
Gorkha              Math   Polygender
Lalitpur      Multimedia       Female
Chitwan               IT         Male
Janakpur      Multimedia       Female
Jhapa                 IT         Male
Lalitpur         English       Female
Gorkha      Data science       Female
Janakpur            Math       Female
Gorkha      Data science   Non-binary
Jhapa               Math       Female
Lalitpur    Data science         Male
Kathmandu           Math       Female
Jhapa               Math       Female
Chitwan          English         Male
Biratnagar  Data science     Bigender
Chitwan               IT         Male
Gorkha           English         Male
Biratnagar            IT         Male
Gorkha              Math         Male
Chitwan          English         Male
Kathmandu             IT         Male
Kathmandu     Multimedia         Male
Bhaktapur             IT         Male
Kathmandu     Multimedia       Female
Lalitpur              IT      Agender
Gorkha           English       Female
Gorkha                IT         Male
Gorkha           English       Female
Lalitpur      Multimedia       Female
Jhapa               Math         Male
Janakpur    Data science      Agender
Janakpur      Multimedia         Male
Gorkha              Math       Female
Jhapa         Multimedia         Male
Bhaktapur             IT         Male
Bhaktapur           Math         Male
Gorkha           English       Female
Gorkha        Multimedia       Female
Biratnagar    Multimedia         Male
Biratnagar          Math         Male
Bhaktapur           Math       Female
Jhapa                 IT         Male
Chitwan     Data science         Male
Chitwan     Data science         Male
Gorkha              Math       Female
Chitwan       Multimedia       Female
Chitwan          English       Female
Janakpur         English         Male
Jhapa            English       Female
Chitwan             Math         Male
Jhapa            English       Female
Jhapa         Multimedia         Male
Biratnagar       English         Male
Chitwan     Data science         Male
Biratnagar  Data science       Female
Gorkha        Multimedia      Agender
Biratnagar          Math       Female
Biratnagar  Data science       Female
Lalitpur              IT      Agender
Bhaktapur             IT         Male
Kathmandu             IT       Female
Biratnagar            IT         Male
Jhapa         Multimedia       Female
Lalitpur            Math       Female
Biratnagar    Multimedia         Male
Janakpur         English       Female
Chitwan       Multimedia       Female
Janakpur         English       Female
Jhapa         Multimedia       Female
Chitwan       Multimedia         Male
Bhaktapur             IT       Female
Lalitpur            Math         Male
Jhapa            English         Male
Kathmandu     Multimedia         Male
Janakpur      Multimedia         Male
Gorkha      Data science       Female
Jhapa         Multimedia   Polygender
Lalitpur    Data science         Male
Kathmandu           Math       Female
Chitwan               IT       Female
Bhaktapur     Multimedia         Male
Janakpur              IT       Female
Biratnagar       English       Female
Chitwan     Data science   Non-binary
Lalitpur            Math         Male
Gorkha           English   Non-binary
Gorkha      Data science   Polygender
Biratnagar          Math       Female
Biratnagar       English         Male
Biratnagar       English         Male
Bhaktapur             IT         Male
Chitwan     Data science         Male
Kathmandu     Multimedia     Bigender
Gorkha           English         Male
Jhapa         Multimedia       Female
Janakpur              IT       Female
Biratnagar  Data science         Male
Biratnagar  Data science         Male
Chitwan     Data science       Female
Janakpur              IT       Female
Chitwan             Math         Male
Gorkha      Data science         Male
Gorkha           English         Male
Jhapa            English       Female
Chitwan             Math       Female
Kathmandu   Data science         Male
Chitwan       Multimedia         Male
Biratnagar            IT  Genderqueer
Lalitpur            Math       Female
Gorkha      Data science         Male
Kathmandu     Multimedia       Female
Janakpur      Multimedia         Male
Kathmandu     Multimedia         Male
Janakpur    Data science       Female
Jhapa                 IT       Female
Chitwan     Data science       Female
Kathmandu        English       Female
Jhapa                 IT         Male
Kathmandu        English  Genderfluid
Jhapa       Data science         Male
Biratnagar  Data science       Female
Biratnagar    Multimedia   Non-binary
Chitwan     Data science         Male
Biratnagar            IT       Female
Lalitpur      Multimedia         Male
Gorkha              Math       Female
Chitwan             Math       Female
Janakpur              IT         Male
Kathmandu             IT         Male
Gorkha      Data science         Male
Gorkha        Multimedia       Female
Gorkha                IT         Male
Bhaktapur        English         Male
Janakpur              IT       Female
Biratnagar    Multimedia       Female
Bhaktapur        English       Female
Janakpur      Multimedia     Bigender
Bhaktapur           Math       Female
Bhaktapur     Multimedia       Female
Janakpur      Multimedia       Female
Gorkha      Data science       Female

In [8]:
#df.filter(items = ['Lalitpur'], axis = 0)

# Select all rows where address == 'Lalitpur'
df_lalitpur = df[df['address'] == 'Lalitpur']
df_lalitpur

,id,fullname,section,subject,email,Unnamed: 5,address,gender
1,948,Rurik Acuna,A,Data science,racuna1@who.int,password,Lalitpur,Male
10,807,Micaela De Goey,E,Multimedia,mdea@infoseek.co.jp,password,Lalitpur,Female
14,806,Mellisa Tomich,C,English,mtomiche@aol.com,password,Lalitpur,Female
19,296,Archaimbaud Kulis,D,Data science,akulisj@jiathis.com,password,Lalitpur,Male
33,96,Gordy Cobbald,C,IT,gcobbaldx@forbes.com,password,Lalitpur,Agender
37,166,Herminia Gagen,E,Multimedia,hgagen11@whitehouse.gov,password,Lalitpur,Female
67,515,Irina Lowth,A,IT,ilowth1v@free.fr,password,Lalitpur,Agender
72,746,Emma Piele,A,Math,epiele20@dailymotion.com,password,Lalitpur,Female
80,442,Sinclair Calleja,B,Math,scalleja28@msu.edu,password,Lalitpur,Male
86,884,Mychal Legister,B,Data science,mlegister2e@shop-pro.jp,password,Lalitpur,Male
93,121,Phineas Seywood,D,Math,pseywood2l@slideshare.net,password,Lalitpur,Male
117,298,Henka Creighton,D,Math,hcreighton39@psu.edu,password,Lalitpur,Female
133,34,Tomas L' Estrange,D,Multimedia,tl3p@wikispaces.com,password,Lalitpur,Male

In [10]:
df[df['id'] < 50].sort_values(by='id', ascending=False)

,id,fullname,section,subject,email,Unnamed: 5,address,gender
11,44,Dana Symes,B,IT,dsymesb@cnet.com,password,Chitwan,Male
78,41,Boonie Gratten,E,Multimedia,bgratten26@japanpost.jp,password,Chitwan,Male
133,34,Tomas L' Estrange,D,Multimedia,tl3p@wikispaces.com,password,Lalitpur,Male
16,21,Shanta Slee,D,Math,ssleeg@php.net,password,Janakpur,Female
110,16,Serge Reap,C,Data science,sreap32@ft.com,password,Gorkha,Male
84,13,Evelina Eady,A,Data science,eeady2c@geocities.com,password,Gorkha,Female
60,11,Frasco Shelsher,B,Multimedia,fshelsher1o@clickbank.net,password,Jhapa,Male
145,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Janakpur,Bigender

In [12]:
df[df['id'] < 50].sort_values(by=['id', 'subject'], ascending=[False, True])

,id,fullname,section,subject,email,Unnamed: 5,address,gender
11,44,Dana Symes,B,IT,dsymesb@cnet.com,password,Chitwan,Male
78,41,Boonie Gratten,E,Multimedia,bgratten26@japanpost.jp,password,Chitwan,Male
133,34,Tomas L' Estrange,D,Multimedia,tl3p@wikispaces.com,password,Lalitpur,Male
16,21,Shanta Slee,D,Math,ssleeg@php.net,password,Janakpur,Female
110,16,Serge Reap,C,Data science,sreap32@ft.com,password,Gorkha,Male
84,13,Evelina Eady,A,Data science,eeady2c@geocities.com,password,Gorkha,Female
60,11,Frasco Shelsher,B,Multimedia,fshelsher1o@clickbank.net,password,Jhapa,Male
145,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Janakpur,Bigender

In [33]:
df = pd.read_csv(r"C:\Users\ASUS\Desktop\DataPy\user.csv", index_col = 'id')

In [34]:
df

,fullname,section,subject,email,Unnamed: 5,address,gender
id,,,,,,,
372,Astrid Spittal,B,Multimedia,aspittal0@cbsnews.com,password,Janakpur,Female
948,Rurik Acuna,A,Data science,racuna1@who.int,password,Lalitpur,Male
655,Gerhardine Lindenberg,E,Data science,glindenberg2@shinystat.com,password,Bhaktapur,Female
532,Bran Rands,E,Multimedia,brands3@cpanel.net,password,Gorkha,Male
69,Daffie Childs,C,Data science,dchilds4@furl.net,password,Kathmandu,Female
...,...,...,...,...,...,...,...
7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Janakpur,Bigender
515,Andi Smethurst,C,Math,asmethurst42@sun.com,password,Bhaktapur,Female
640,Clarissa Drinkale,C,Multimedia,cdrinkale43@nifty.com,password,Bhaktapur,Female
986,Rubetta Barrass,D,Multimedia,rbarrass44@blogtalkradio.com,password,Janakpur,Female
740,Zonda Adnett,A,Data science,zadnett45@shinystat.com,password,Gorkha,Female

In [17]:
df.reset_index(inplace = True)
df

,index,id,fullname,section,subject,email,Unnamed: 5,address,gender
0,0,372,Astrid Spittal,B,Multimedia,aspittal0@cbsnews.com,password,Janakpur,Female
1,1,948,Rurik Acuna,A,Data science,racuna1@who.int,password,Lalitpur,Male
2,2,655,Gerhardine Lindenberg,E,Data science,glindenberg2@shinystat.com,password,Bhaktapur,Female
3,3,532,Bran Rands,E,Multimedia,brands3@cpanel.net,password,Gorkha,Male
4,4,69,Daffie Childs,C,Data science,dchilds4@furl.net,password,Kathmandu,Female
...,...,...,...,...,...,...,...,...,...
145,145,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Janakpur,Bigender
146,146,515,Andi Smethurst,C,Math,asmethurst42@sun.com,password,Bhaktapur,Female
147,147,640,Clarissa Drinkale,C,Multimedia,cdrinkale43@nifty.com,password,Bhaktapur,Female
148,148,986,Rubetta Barrass,D,Multimedia,rbarrass44@blogtalkradio.com,password,Janakpur,Female
149,149,740,Zonda Adnett,A,Data science,zadnett45@shinystat.com,password,Gorkha,Female

In [18]:
df.set_index("address")

,index,id,fullname,section,subject,email,Unnamed: 5,gender
address,,,,,,,,
Janakpur,0,372,Astrid Spittal,B,Multimedia,aspittal0@cbsnews.com,password,Female
Lalitpur,1,948,Rurik Acuna,A,Data science,racuna1@who.int,password,Male
Bhaktapur,2,655,Gerhardine Lindenberg,E,Data science,glindenberg2@shinystat.com,password,Female
Gorkha,3,532,Bran Rands,E,Multimedia,brands3@cpanel.net,password,Male
Kathmandu,4,69,Daffie Childs,C,Data science,dchilds4@furl.net,password,Female
...,...,...,...,...,...,...,...,...
Janakpur,145,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Bigender
Bhaktapur,146,515,Andi Smethurst,C,Math,asmethurst42@sun.com,password,Female
Bhaktapur,147,640,Clarissa Drinkale,C,Multimedia,cdrinkale43@nifty.com,password,Female
Janakpur,148,986,Rubetta Barrass,D,Multimedia,rbarrass44@blogtalkradio.com,password,Female
Gorkha,149,740,Zonda Adnett,A,Data science,zadnett45@shinystat.com,password,Female

In [19]:
df.set_index("address", inplace = True)

In [20]:
df

,index,id,fullname,section,subject,email,Unnamed: 5,gender
address,,,,,,,,
Janakpur,0,372,Astrid Spittal,B,Multimedia,aspittal0@cbsnews.com,password,Female
Lalitpur,1,948,Rurik Acuna,A,Data science,racuna1@who.int,password,Male
Bhaktapur,2,655,Gerhardine Lindenberg,E,Data science,glindenberg2@shinystat.com,password,Female
Gorkha,3,532,Bran Rands,E,Multimedia,brands3@cpanel.net,password,Male
Kathmandu,4,69,Daffie Childs,C,Data science,dchilds4@furl.net,password,Female
...,...,...,...,...,...,...,...,...
Janakpur,145,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Bigender
Bhaktapur,146,515,Andi Smethurst,C,Math,asmethurst42@sun.com,password,Female
Bhaktapur,147,640,Clarissa Drinkale,C,Multimedia,cdrinkale43@nifty.com,password,Female
Janakpur,148,986,Rubetta Barrass,D,Multimedia,rbarrass44@blogtalkradio.com,password,Female
Gorkha,149,740,Zonda Adnett,A,Data science,zadnett45@shinystat.com,password,Female

In [21]:
df.loc['Janakpur']

,index,id,fullname,section,subject,email,Unnamed: 5,gender
address,,,,,,,,
Janakpur,0,372,Astrid Spittal,B,Multimedia,aspittal0@cbsnews.com,password,Female
Janakpur,12,328,Cassey Heugle,C,Multimedia,cheuglec@nps.gov,password,Female
Janakpur,16,21,Shanta Slee,D,Math,ssleeg@php.net,password,Female
Janakpur,39,438,Dory Ferdinand,C,Data science,dferdinand13@livejournal.com,password,Agender
Janakpur,40,236,Francis Nott,B,Multimedia,fnott14@wired.com,password,Male
Janakpur,56,587,Lewes Ludlow,C,English,lludlow1k@elegantthemes.com,password,Male
Janakpur,74,513,Rosina Laver,D,English,rlaver22@sfgate.com,password,Female
Janakpur,76,274,Calypso Casley,A,English,ccasley24@networksolutions.com,password,Female
Janakpur,83,64,Omar Pinnick,A,Multimedia,opinnick2b@digg.com,password,Male
Janakpur,90,445,Em Findlow,B,IT,efindlow2i@shop-pro.jp,password,Female
Janakpur,104,406,Una Amps,A,IT,uamps2w@taobao.com,password,Female
Janakpur,108,108,Evangeline Oxbrow,B,IT,eoxbrow30@yahoo.com,password,Female
Janakpur,120,826,Egon Ferryn,B,Multimedia,eferryn3c@weibo.com,password,Male
Janakpur,122,573,Truda Coppen,E,Data science,tcoppen3e@marriott.com,password,Female
Janakpur,136,295,Bryanty Oulet,B,IT,boulet3s@imageshack.us,password,Male
Janakpur,142,635,Gladi Ickovic,B,IT,gickovic3y@trellian.com,password,Female
Janakpur,145,7,Chariot Flattman,B,Multimedia,cflattman41@mac.com,password,Bigender
Janakpur,148,986,Rubetta Barrass,D,Multimedia,rbarrass44@blogtalkradio.com,password,Female

In [22]:
df.iloc[149]

index                             149
id                                740
fullname                 Zonda Adnett
section                             A
subject                  Data science
email         zadnett45@shinystat.com
Unnamed: 5                   password
gender                         Female
Name: Gorkha, dtype: object

In [24]:
df.set_index(['id','subject'], inplace = True)

In [25]:
df

,,index,fullname,section,email,Unnamed: 5,gender
id,subject,,,,,,
372,Multimedia,0,Astrid Spittal,B,aspittal0@cbsnews.com,password,Female
948,Data science,1,Rurik Acuna,A,racuna1@who.int,password,Male
655,Data science,2,Gerhardine Lindenberg,E,glindenberg2@shinystat.com,password,Female
532,Multimedia,3,Bran Rands,E,brands3@cpanel.net,password,Male
69,Data science,4,Daffie Childs,C,dchilds4@furl.net,password,Female
...,...,...,...,...,...,...,...
7,Multimedia,145,Chariot Flattman,B,cflattman41@mac.com,password,Bigender
515,Math,146,Andi Smethurst,C,asmethurst42@sun.com,password,Female
640,Multimedia,147,Clarissa Drinkale,C,cdrinkale43@nifty.com,password,Female
986,Multimedia,148,Rubetta Barrass,D,rbarrass44@blogtalkradio.com,password,Female
740,Data science,149,Zonda Adnett,A,zadnett45@shinystat.com,password,Female

In [26]:
df.sort_index()

,,index,fullname,section,email,Unnamed: 5,gender
id,subject,,,,,,
7,Multimedia,145,Chariot Flattman,B,cflattman41@mac.com,password,Bigender
11,Multimedia,60,Frasco Shelsher,B,fshelsher1o@clickbank.net,password,Male
13,Data science,84,Evelina Eady,A,eeady2c@geocities.com,password,Female
16,Data science,110,Serge Reap,C,sreap32@ft.com,password,Male
21,Math,16,Shanta Slee,D,ssleeg@php.net,password,Female
...,...,...,...,...,...,...,...
955,Data science,124,Jaquenetta Attenbarrow,D,jattenbarrow3g@samsung.com,password,Female
964,IT,88,Maggee Dudney,E,mdudney2g@icio.us,password,Female
965,English,141,Far Molineaux,E,fmolineaux3x@dedecms.com,password,Male
983,IT,70,Pedro Vlasin,A,pvlasin1y@wikimedia.org,password,Male
986,Multimedia,148,Rubetta Barrass,D,rbarrass44@blogtalkradio.com,password,Female

In [28]:
pd.set_option('display.max_columns', 200)

In [29]:
pd

In [30]:
df

,,index,fullname,section,email,Unnamed: 5,gender
id,subject,,,,,,
372,Multimedia,0,Astrid Spittal,B,aspittal0@cbsnews.com,password,Female
948,Data science,1,Rurik Acuna,A,racuna1@who.int,password,Male
655,Data science,2,Gerhardine Lindenberg,E,glindenberg2@shinystat.com,password,Female
532,Multimedia,3,Bran Rands,E,brands3@cpanel.net,password,Male
69,Data science,4,Daffie Childs,C,dchilds4@furl.net,password,Female
...,...,...,...,...,...,...,...
7,Multimedia,145,Chariot Flattman,B,cflattman41@mac.com,password,Bigender
515,Math,146,Andi Smethurst,C,asmethurst42@sun.com,password,Female
640,Multimedia,147,Clarissa Drinkale,C,cdrinkale43@nifty.com,password,Female
986,Multimedia,148,Rubetta Barrass,D,rbarrass44@blogtalkradio.com,password,Female
740,Data science,149,Zonda Adnett,A,zadnett45@shinystat.com,password,Female

In [35]:
df.set_index("address", inplace=True)

# Now you can query by address
df.loc["Janakpur", "subject"]
df.loc["Kathmandu", "subject"]

address
Kathmandu    Data science
Kathmandu            Math
Kathmandu            Math
Kathmandu              IT
Kathmandu      Multimedia
Kathmandu      Multimedia
Kathmandu              IT
Kathmandu      Multimedia
Kathmandu            Math
Kathmandu      Multimedia
Kathmandu    Data science
Kathmandu      Multimedia
Kathmandu      Multimedia
Kathmandu         English
Kathmandu         English
Kathmandu              IT
Name: subject, dtype: object

In [40]:
#Group by and aggregration

group_by_frame = df.groupby("address").mean(numeric_only=True)

In [41]:
group_by_frame

Empty DataFrame
Columns: []
Index: [Bhaktapur, Biratnagar, Chitwan, Gorkha, Janakpur, Jhapa, Kathmandu, Lalitpur]

In [44]:
group_by_frame = df.groupby("subject").count()
group_by_frame

              fullname  section  email  Unnamed: 5  gender
subject
Data science        31       31     31          31      31
English             28       28     28          28      28
IT                  28       28     28          28      28
Math                26       26     26          26      26
Multimedia          37       37     37          37      37

In [45]:
group_by_frame = df.groupby("subject").max()
group_by_frame

,fullname,section,email,Unnamed: 5,gender
subject,,,,,
Data science,Zonda Adnett,E,zadnett45@shinystat.com,password,Polygender
English,Zacherie Usher,E,zusher2p@cdbaby.com,password,Non-binary
IT,Yehudit Snazel,E,ysnazelt@chicagotribune.com,password,Male
Math,Thomasin Longcake,E,tlongcake2o@amazon.de,password,Polygender
Multimedia,Tonie Croft,E,tsmewing3b@t-online.de,password,Polygender

In [46]:
group_by_frame = df.groupby("subject").min()
group_by_frame

,fullname,section,email,Unnamed: 5,gender
subject,,,,,
Data science,Alix Forrington,A,aforringtonh@pagesperso-orange.fr,password,Agender
English,Adrianne Meaden,A,ameaden34@comcast.net,password,Female
IT,Alasdair Padbury,A,apadburyv@senate.gov,password,Agender
Math,Abagail Wyllt,A,acowins9@nsw.gov.au,password,Female
Multimedia,Aarika Peacher,A,abrewis23@paypal.com,password,Agender

In [47]:
group_by_frame = df.groupby("subject").sum()
group_by_frame

,fullname,section,email,Unnamed: 5,gender
subject,,,,,
Data science,Rurik AcunaGerhardine LindenbergDaffie ChildsA...,AECACDBCCDDBCABDACEDECCCEDCBABA,racuna1@who.intglindenberg2@shinystat.comdchil...,passwordpasswordpasswordpasswordpasswordpasswo...,MaleFemaleFemaleFemaleNon-binaryMaleBigenderAg...
English,Cooper FernihoughMarv RederMellisa TomichGabi ...,DCCDDEAEDECDEADACDDCBBEABEEA,cfernihough5@geocities.jpmreder7@dmoz.orgmtomi...,passwordpasswordpasswordpasswordpasswordpasswo...,MaleMaleFemaleMaleMaleMaleFemaleFemaleFemaleFe...
IT,Dana SymesRic MatusiakMaddy CorringhamHillier ...,BBEAEBCBEBABCACEBDABCEDEBBBB,dsymesb@cnet.comrmatusiakd@etsy.commcorringham...,passwordpasswordpasswordpasswordpasswordpasswo...,MaleMaleMaleMaleMaleMaleAgenderMaleMaleMaleAge...
Math,Bendicty MordacaiAndrus CowinsShanta SleeShann...,CBDBDEDDABCEDBDABADCEADCCC,bmordacai8@canalblog.comacowins9@nsw.gov.aussl...,passwordpasswordpasswordpasswordpasswordpasswo...,MalePolygenderFemaleFemaleFemaleFemaleMaleMale...
Multimedia,Astrid SpittalBran RandsCarlee GirardyMicaela ...,BEAECCEEBECAEBCBDBDECACCBEEBBCDDAABCD,aspittal0@cbsnews.combrands3@cpanel.netcgirard...,passwordpasswordpasswordpasswordpasswordpasswo...,FemaleMaleFemaleFemaleFemaleMaleFemaleFemaleMa...

In [50]:
group_by_frame = df.groupby("subject").agg({
    "marks": ["mean", "min", "max", "count", "sum"]
})
group_by_frame

                  marks
                   mean min  max count   sum
subject
Data science  86.000000  70  100    25  2150
English       85.000000  70  100    36  3060
IT            84.138889  73   99    36  3029
Math          87.173913  70   99    23  2005
Multimedia    82.900000  70  100    30  2487

df.groupby(["marks","Liked"]).mean(numeric_only=True)

In [52]:
df

,id,fullname,section,subject,email,marks
0,653,Nichole Carbett,D,English,ncarbett0@booking.com,78
1,680,Lonnie Slocomb,A,Multimedia,lslocomb1@arizona.edu,82
2,773,Maggee Casbourne,C,IT,mcasbourne2@yelp.com,75
3,485,Quintina Tripney,B,Multimedia,qtripney3@zdnet.com,90
4,36,Dione Dalman,D,English,ddalman4@multiply.com,90
...,...,...,...,...,...,...
145,924,Balduin Hanham,C,English,bhanham41@mail.ru,77
146,553,Dalli Jirieck,A,Multimedia,djirieck42@gnu.org,89
147,540,Paulette Rapaport,E,IT,prapaport43@usgs.gov,84
148,411,Theadora Tweed,D,Data science,ttweed44@tiny.cc,72
149,298,Malissa Daniels,D,Data science,mdaniels45@purevolume.com,96

In [53]:
df.groupby('subject').describe()

                id                                                       \
             count        mean         std   min     25%    50%     75%
subject
Data science  25.0  540.720000  342.724321   7.0  162.00  684.0  798.00
English       36.0  472.305556  315.221357  25.0  186.50  468.5  713.00
IT            36.0  530.250000  261.840559  53.0  309.25  559.5  681.75
Math          23.0  529.130435  308.344451   4.0  318.50  449.0  816.50
Multimedia    30.0  484.200000  273.044698  65.0  273.00  490.0  674.50

                    marks
                max count       mean       std   min   25%   50%    75%    max
subject
Data science  993.0  25.0  86.000000  9.591663  70.0  78.0  86.0  94.00  100.0
English       958.0  36.0  85.000000  9.289010  70.0  77.0  85.0  93.50  100.0
IT            979.0  36.0  84.138889  8.198093  73.0  77.5  83.5  88.75   99.0
Math          986.0  23.0  87.173913  9.276815  70.0  78.0  90.0  94.50   99.0
Multimedia    981.0  30.0  82.900000  9.732101  70.0  73.5  83.0  89.75  100.0