In [1]:
#MERGE , JOIN AND CONCATENATE
import pandas as pd

In [2]:
df1 = pd.read_csv(r"C:\Users\ASUS\Desktop\DataPy\patients.csv")

In [3]:
df1

   patient_id   name  age        city
0           1  Aisha   21   Kathmandu
1           2  Rohan   24     Pokhara
2           3   Sita   22  Biratnagar
3           4  Arjun   25      Butwal
4           5   Mina   23    Lalitpur
5           6  Kiran   26     Chitwan

In [4]:
df2 = pd.read_csv(r"C:\Users\ASUS\Desktop\DataPy\appointments.csv")
df2

   appointment_id  patient_id appointment_date       doctor
0             101           1       2026-06-10    Dr Sharma
1             102           2       2026-06-11    Dr Khanal
2             103           1       2026-06-15    Dr Sharma
3             104           4       2026-06-16  Dr Adhikari
4             105           7       2026-06-17       Dr Rai

In [6]:
df1.merge(df2)  #inner join

,patient_id,name,age,city,appointment_id,appointment_date,doctor
0,1,Aisha,21,Kathmandu,101,2026-06-10,Dr Sharma
1,1,Aisha,21,Kathmandu,103,2026-06-15,Dr Sharma
2,2,Rohan,24,Pokhara,102,2026-06-11,Dr Khanal
3,4,Arjun,25,Butwal,104,2026-06-16,Dr Adhikari

In [7]:
df1.merge(df2, how = 'inner')

,patient_id,name,age,city,appointment_id,appointment_date,doctor
0,1,Aisha,21,Kathmandu,101,2026-06-10,Dr Sharma
1,1,Aisha,21,Kathmandu,103,2026-06-15,Dr Sharma
2,2,Rohan,24,Pokhara,102,2026-06-11,Dr Khanal
3,4,Arjun,25,Butwal,104,2026-06-16,Dr Adhikari

In [11]:
df1.merge(df2, how = 'inner', on ='patient_id')

,patient_id,name,age,city,appointment_id,appointment_date,doctor
0,1,Aisha,21,Kathmandu,101,2026-06-10,Dr Sharma
1,1,Aisha,21,Kathmandu,103,2026-06-15,Dr Sharma
2,2,Rohan,24,Pokhara,102,2026-06-11,Dr Khanal
3,4,Arjun,25,Butwal,104,2026-06-16,Dr Adhikari

In [12]:
df1.merge(df2, how = 'outer')

,patient_id,name,age,city,appointment_id,appointment_date,doctor
0,1,Aisha,21.0,Kathmandu,101.0,2026-06-10,Dr Sharma
1,1,Aisha,21.0,Kathmandu,103.0,2026-06-15,Dr Sharma
2,2,Rohan,24.0,Pokhara,102.0,2026-06-11,Dr Khanal
3,3,Sita,22.0,Biratnagar,NaN,NaN,NaN
4,4,Arjun,25.0,Butwal,104.0,2026-06-16,Dr Adhikari
5,5,Mina,23.0,Lalitpur,NaN,NaN,NaN
6,6,Kiran,26.0,Chitwan,NaN,NaN,NaN
7,7,NaN,NaN,NaN,105.0,2026-06-17,Dr Rai

In [16]:
merged_df = df1.merge(df2, how='left', on='patient_id')
merged_df

,patient_id,name,age,city,appointment_id,appointment_date,doctor
0,1,Aisha,21,Kathmandu,101.0,2026-06-10,Dr Sharma
1,1,Aisha,21,Kathmandu,103.0,2026-06-15,Dr Sharma
2,2,Rohan,24,Pokhara,102.0,2026-06-11,Dr Khanal
3,3,Sita,22,Biratnagar,NaN,NaN,NaN
4,4,Arjun,25,Butwal,104.0,2026-06-16,Dr Adhikari
5,5,Mina,23,Lalitpur,NaN,NaN,NaN
6,6,Kiran,26,Chitwan,NaN,NaN,NaN

In [17]:
merged_df = df1.merge(df2, how='right', on='patient_id')
merged_df

,patient_id,name,age,city,appointment_id,appointment_date,doctor
0,1,Aisha,21.0,Kathmandu,101,2026-06-10,Dr Sharma
1,2,Rohan,24.0,Pokhara,102,2026-06-11,Dr Khanal
2,1,Aisha,21.0,Kathmandu,103,2026-06-15,Dr Sharma
3,4,Arjun,25.0,Butwal,104,2026-06-16,Dr Adhikari
4,7,NaN,NaN,NaN,105,2026-06-17,Dr Rai

In [20]:
df = df1.merge(df2, how='cross')
df

,patient_id_x,name,age,city,appointment_id,patient_id_y,appointment_date,doctor
0,1,Aisha,21,Kathmandu,101,1,2026-06-10,Dr Sharma
1,1,Aisha,21,Kathmandu,102,2,2026-06-11,Dr Khanal
2,1,Aisha,21,Kathmandu,103,1,2026-06-15,Dr Sharma
3,1,Aisha,21,Kathmandu,104,4,2026-06-16,Dr Adhikari
4,1,Aisha,21,Kathmandu,105,7,2026-06-17,Dr Rai
5,2,Rohan,24,Pokhara,101,1,2026-06-10,Dr Sharma
6,2,Rohan,24,Pokhara,102,2,2026-06-11,Dr Khanal
7,2,Rohan,24,Pokhara,103,1,2026-06-15,Dr Sharma
8,2,Rohan,24,Pokhara,104,4,2026-06-16,Dr Adhikari
9,2,Rohan,24,Pokhara,105,7,2026-06-17,Dr Rai
10,3,Sita,22,Biratnagar,101,1,2026-06-10,Dr Sharma
11,3,Sita,22,Biratnagar,102,2,2026-06-11,Dr Khanal
12,3,Sita,22,Biratnagar,103,1,2026-06-15,Dr Sharma
13,3,Sita,22,Biratnagar,104,4,2026-06-16,Dr Adhikari
14,3,Sita,22,Biratnagar,105,7,2026-06-17,Dr Rai
15,4,Arjun,25,Butwal,101,1,2026-06-10,Dr Sharma
16,4,Arjun,25,Butwal,102,2,2026-06-11,Dr Khanal
17,4,Arjun,25,Butwal,103,1,2026-06-15,Dr Sharma
18,4,Arjun,25,Butwal,104,4,2026-06-16,Dr Adhikari
19,4,Arjun,25,Butwal,105,7,2026-06-17,Dr Rai
20,5,Mina,23,Lalitpur,101,1,2026-06-10,Dr Sharma
21,5,Mina,23,Lalitpur,102,2,2026-06-11,Dr Khanal
22,5,Mina,23,Lalitpur,103,1,2026-06-15,Dr Sharma
23,5,Mina,23,Lalitpur,104,4,2026-06-16,Dr Adhikari
24,5,Mina,23,Lalitpur,105,7,2026-06-17,Dr Rai
25,6,Kiran,26,Chitwan,101,1,2026-06-10,Dr Sharma
26,6,Kiran,26,Chitwan,102,2,2026-06-11,Dr Khanal
27,6,Kiran,26,Chitwan,103,1,2026-06-15,Dr Sharma
28,6,Kiran,26,Chitwan,104,4,2026-06-16,Dr Adhikari
29,6,Kiran,26,Chitwan,105,7,2026-06-17,Dr Rai

In [21]:
df1.join(df2, on = 'patient_id', how = 'outer', lsuffix = '_Left',rsuffix = '_Right')

,patient_id,patient_id_Left,name,age,city,appointment_id,patient_id_Right,appointment_date,doctor
NaN,0,NaN,NaN,NaN,NaN,101.0,1.0,2026-06-10,Dr Sharma
0.0,1,1.0,Aisha,21.0,Kathmandu,102.0,2.0,2026-06-11,Dr Khanal
1.0,2,2.0,Rohan,24.0,Pokhara,103.0,1.0,2026-06-15,Dr Sharma
2.0,3,3.0,Sita,22.0,Biratnagar,104.0,4.0,2026-06-16,Dr Adhikari
3.0,4,4.0,Arjun,25.0,Butwal,105.0,7.0,2026-06-17,Dr Rai
4.0,5,5.0,Mina,23.0,Lalitpur,NaN,NaN,NaN,NaN
5.0,6,6.0,Kiran,26.0,Chitwan,NaN,NaN,NaN,NaN

In [23]:
df4 = df1.set_index('patient_id').join(df2.set_index('patient_id'), lsuffix = '_Left', rsuffix = '_Right', how = 'outer')
df4

,name,age,city,appointment_id,appointment_date,doctor
patient_id,,,,,,
1,Aisha,21.0,Kathmandu,101.0,2026-06-10,Dr Sharma
1,Aisha,21.0,Kathmandu,103.0,2026-06-15,Dr Sharma
2,Rohan,24.0,Pokhara,102.0,2026-06-11,Dr Khanal
3,Sita,22.0,Biratnagar,NaN,NaN,NaN
4,Arjun,25.0,Butwal,104.0,2026-06-16,Dr Adhikari
5,Mina,23.0,Lalitpur,NaN,NaN,NaN
6,Kiran,26.0,Chitwan,NaN,NaN,NaN
7,NaN,NaN,NaN,105.0,2026-06-17,Dr Rai

In [26]:
pd.concat([df1,df2], join = 'inner')

   patient_id
0           1
1           2
2           3
3           4
4           5
5           6
0           1
1           2
2           1
3           4
4           7

In [27]:
pd.concat([df1,df2], join = 'outer')

,patient_id,name,age,city,appointment_id,appointment_date,doctor
0,1,Aisha,21.0,Kathmandu,NaN,NaN,NaN
1,2,Rohan,24.0,Pokhara,NaN,NaN,NaN
2,3,Sita,22.0,Biratnagar,NaN,NaN,NaN
3,4,Arjun,25.0,Butwal,NaN,NaN,NaN
4,5,Mina,23.0,Lalitpur,NaN,NaN,NaN
5,6,Kiran,26.0,Chitwan,NaN,NaN,NaN
0,1,NaN,NaN,NaN,101.0,2026-06-10,Dr Sharma
1,2,NaN,NaN,NaN,102.0,2026-06-11,Dr Khanal
2,1,NaN,NaN,NaN,103.0,2026-06-15,Dr Sharma
3,4,NaN,NaN,NaN,104.0,2026-06-16,Dr Adhikari
4,7,NaN,NaN,NaN,105.0,2026-06-17,Dr Rai

In [28]:
pd.concat([df1,df2], join = 'inner', axis = 1)

,patient_id,name,age,city,appointment_id,patient_id,appointment_date,doctor
0,1,Aisha,21,Kathmandu,101,1,2026-06-10,Dr Sharma
1,2,Rohan,24,Pokhara,102,2,2026-06-11,Dr Khanal
2,3,Sita,22,Biratnagar,103,1,2026-06-15,Dr Sharma
3,4,Arjun,25,Butwal,104,4,2026-06-16,Dr Adhikari
4,5,Mina,23,Lalitpur,105,7,2026-06-17,Dr Rai

In [29]:
pd.concat([df1,df2])

,patient_id,name,age,city,appointment_id,appointment_date,doctor
0,1,Aisha,21.0,Kathmandu,NaN,NaN,NaN
1,2,Rohan,24.0,Pokhara,NaN,NaN,NaN
2,3,Sita,22.0,Biratnagar,NaN,NaN,NaN
3,4,Arjun,25.0,Butwal,NaN,NaN,NaN
4,5,Mina,23.0,Lalitpur,NaN,NaN,NaN
5,6,Kiran,26.0,Chitwan,NaN,NaN,NaN
0,1,NaN,NaN,NaN,101.0,2026-06-10,Dr Sharma
1,2,NaN,NaN,NaN,102.0,2026-06-11,Dr Khanal
2,1,NaN,NaN,NaN,103.0,2026-06-15,Dr Sharma
3,4,NaN,NaN,NaN,104.0,2026-06-16,Dr Adhikari
4,7,NaN,NaN,NaN,105.0,2026-06-17,Dr Rai

In [31]:
#append removed from pandas u can use concat for ame operations!!

AttributeError: 'DataFrame' object has no attribute 'append'