In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dirty_transactions.csv")

In [3]:
df.head(10)

  transaction_id customer_segment     transaction_date state   amount
0       TXN_5000       Enterprise  2024-05-01 00:00:00    CA  1842.10
1       TXN_5001              SMB  2024-05-01 12:00:00    NY   340.50
2       TXN_5002         Consumer  2024-05-02 00:00:00    TX    85.20
3       TXN_5003       Enterprise  2024-05-02 12:00:00    FL  2100.00
4       TXN_5004              SMB  2024-05-03 00:00:00    CA      NaN
5       TXN_5005         Consumer  2024-05-03 12:00:00    IL    42.75
6       TXN_5006       Enterprise  2024-05-04 00:00:00    NY  1550.00
7       TXN_5007              SMB  2024-05-04 12:00:00    TX   410.80
8       TXN_5008         Consumer  2024-05-05 00:00:00    FL  -120.50
9       TXN_5009       Enterprise  2024-05-05 12:00:00    IL  1980.25

In [4]:
df.tail(10)

   transaction_id customer_segment     transaction_date state  amount
10       TXN_5010              SMB  2024-05-06 00:00:00    CA   275.0
11       TXN_5011       Enterprise  2024-05-06 12:00:00    NY  -999.0
12       TXN_5012         Consumer  2024-05-07 00:00:00    TX   110.0
13       TXN_5013              SMB  2024-05-07 12:00:00    FL   520.4
14       TXN_5014       Enterprise  2024-05-08 00:00:00    CA  2400.0
15       TXN_5015         Consumer  2024-05-08 12:00:00    IL    15.5
16       TXN_5016              SMB  2024-05-09 00:00:00    NY   190.0
17       TXN_5017       Enterprise  2024-05-09 12:00:00    TX  1750.6
18       TXN_5018         Consumer  2024-05-10 00:00:00    CA     NaN
19       TXN_5019              SMB  2024-05-10 12:00:00    FL   380.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     str
 1   customer_segment  20 non-null     str
 2   transaction_date  20 non-null     str
 3   state             20 non-null     str
 4   amount            18 non-null     float64
dtypes: float64(1), str(4)
memory usage: 932.0 bytes

In [6]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"])

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     str
 1   customer_segment  20 non-null     str
 2   transaction_date  20 non-null     datetime64[us]
 3   state             20 non-null     str
 4   amount            18 non-null     float64
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 932.0 bytes

In [8]:
df["amount"] = df["amount"].fillna(df.groupby("customer_segment")["amount"].transform("median"))

In [9]:
df

   transaction_id customer_segment    transaction_date state   amount
0        TXN_5000       Enterprise 2024-05-01 00:00:00    CA  1842.10
1        TXN_5001              SMB 2024-05-01 12:00:00    NY   340.50
2        TXN_5002         Consumer 2024-05-02 00:00:00    TX    85.20
3        TXN_5003       Enterprise 2024-05-02 12:00:00    FL  2100.00
4        TXN_5004              SMB 2024-05-03 00:00:00    CA   360.25
5        TXN_5005         Consumer 2024-05-03 12:00:00    IL    42.75
6        TXN_5006       Enterprise 2024-05-04 00:00:00    NY  1550.00
7        TXN_5007              SMB 2024-05-04 12:00:00    TX   410.80
8        TXN_5008         Consumer 2024-05-05 00:00:00    FL  -120.50
9        TXN_5009       Enterprise 2024-05-05 12:00:00    IL  1980.25
10       TXN_5010              SMB 2024-05-06 00:00:00    CA   275.00
11       TXN_5011       Enterprise 2024-05-06 12:00:00    NY  -999.00
12       TXN_5012         Consumer 2024-05-07 00:00:00    TX   110.00
13       TXN_5013              SMB 2024-05-07 12:00:00    FL   520.40
14       TXN_5014       Enterprise 2024-05-08 00:00:00    CA  2400.00
15       TXN_5015         Consumer 2024-05-08 12:00:00    IL    15.50
16       TXN_5016              SMB 2024-05-09 00:00:00    NY   190.00
17       TXN_5017       Enterprise 2024-05-09 12:00:00    TX  1750.60
18       TXN_5018         Consumer 2024-05-10 00:00:00    CA    42.75
19       TXN_5019              SMB 2024-05-10 12:00:00    FL   380.00

In [10]:
#Outlier/Corrupt Entry Filtering
df_clean = df.loc[df["amount"] >= 0.0].copy()
print("Cleaned Dataset Health Check:")
print(df_clean.info())

Cleaned Dataset Health Check:
<class 'pandas.DataFrame'>
Index: 18 entries, 0 to 19
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    18 non-null     str
 1   customer_segment  18 non-null     str
 2   transaction_date  18 non-null     datetime64[us]
 3   state             18 non-null     str
 4   amount            18 non-null     float64
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 864.0 bytes
None